### ISSUE TITLE
Use patch numbers for patches

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#133]
`coiled-runtime=0.0.3` was re-released with changes. I tried to create a new conda env like so:

```
conda create -n coiled-runtime-003 -c coiled -c conda-forge python=3.8 coiled-runtime=0.0.3 -y
```

And I got the old `coiled-runtime=0.0.3` (with `cloudpickle=2.1`).

Then I ran `conda update -c conda-forge coiled-runtime` and it gave me the updated `coiled-runtime=0.0.3` (with `cloudpickle=2.0`).

This doesn't seem great.

My inclination would be that you never update without bumping the patch number (0.0.x), and you tell people to pin based on minor version (0.x.0). How's that sound?

**Comment by dchudz** [comment]
> tell people to pin based on minor version (0.x.0)

If a patch updates cloudpickle, and people pin the minor version, won't they get software mismatches...?

**Comment by ntabris** [comment]
> If a patch updates cloudpickle, and people pin the minor version, won't they get software mismatches...?

In this case it was adding a version constraint, so if you already had `coiled-runtime=0.0.3` installed it would be unlikely that you'd end up with version mismatch for cloudpickle (you would have had to installed `coiled-runtime=0.0.3` in the window of time after cloudpickle 2.1 came out and before the <=2.0 pin was added). Maybe that's still a concern, though.

That said, yeah, it's probably best to tell people to use exact pin of coiled-runtime.

**Comment by ian-r-rose** [comment]
I agree with using semver and moving the point up as per #194. I generally dislike `0.0.x` versions because they don't leave any room for patch releases in the numbering scheme. This was a persistent thorn in my side when I was release managing the `coiled` package, and to me having a single leading zero `0.x` communicates plenty about the not-fully-mature nature of the package.

**Comment by ncclementi** [comment]
Closing this as we are using semantic versioning now and we have done the release 0.1.0
