### ISSUE TITLE
Add Black formatting to coiled-runtime?

### ISSUE THREAD

**Issue by rrpelgrim** [coiled/coiled-runtime#151]
How would folks feel about adding the Black code formatting libraries to `coiled-runtime`? I find myself adding them to every `coiled-runtime` env, curious if others are doing the same and/or whether we think that is too opinionated of a stance to take here.

See [@MrPowers's blog](https://coiled.io/blog/code-formatting-jupyter-notebooks-with-black/) for context.

**Comment by ntabris** [comment]
My feeling is that I'd like the base `coiled-runtime` to stay slim and a little more focused on code that you'd want on the cluster. Maybe it makes sense to have an expanded env that's "batteries included for local dev" or something like that, though I think you could just pip install `black` or things like that in your local dev on top of the runtime, and then use the regular runtime on cluster.

**Comment by jrbourbeau** [comment]
Thanks for the suggestion @rrpelgrim. In general, I agree with @ntabris that it'd be good to keep the runtime focused on software one would need installed in the cluster for now. FWIW I get the sense you may be a special in your use of `black` -- I associate it more as a software developer tool than a, for example, data scientist tool (I could be wrong here). 

Regardless, there's a conversation happening over in https://github.com/coiled/coiled-runtime/issues/111 around the possibility of adding optional dependencies to the runtime. Let's close this issue and continue the conversation over in https://github.com/coiled/coiled-runtime/issues/111
