### ISSUE TITLE
pip installable coiled-runtime

### ISSUE THREAD

**Issue by dchudz** [coiled/coiled-runtime#153]
I come across a lot of people trying to use Coiled who don't use conda.

Let's consider making a pip installable package for coiled-runtime.

**Comment by ian-r-rose** [comment]
I'm curious about the user profile for people who don't use conda. In my experience it's ubiquitous among data scientists and data analysts, but less so among people who do web/cloud stuff. Is that wrong?

**Comment by ntabris** [comment]
Panorama Ed told me they used poetry.

**Comment by gjoseph92** [comment]
I would love to never have to use conda

**Comment by jrbourbeau** [comment]
@dchudz @ntabris @phobson I'm curious if `coiled-runtime` being `conda`-only is preventing adoption of Coiled. @ntabris you mentioned Panorama Ed -- are there others you've heard this from too? FWIW I think this is a reasonable request, but is currently lower priority than other ongoing work here. However, if this is blocking adoption then we can move it up in the queue

**Comment by dchudz** [comment]
@jrbourbeau I'd turn that question back on you:

Which of our customers are using coiled-runtime regularly in their work? Why or why not?

Asking that question will help us know how much conda-only is a problem, right?

**Comment by dchudz** [comment]
I think the priority is high b/c in the meantime we don't have anything sensible to suggest as a "getting started" flow for non-conda users.

**Comment by dchudz** [comment]
Note that at the moment `pip install coiled-runtime` installs a wheel with... basically nothing in it?

I guess that's because https://github.com/coiled/coiled-runtime/pull/182 isn't done. But kinda confusing for anyone who encounters this in the meantime.

**Comment by jrbourbeau** [comment]
That's correct. I pushed an empty package to ensure we have the `coiled-runtime` name on PyPI
