### ISSUE TITLE
`worker_vm_type` not respected when providing both vm type and `worker_memory` 

### ISSUE THREAD

**Issue by ncclementi** [coiled/coiled-runtime#157]
Currently, in the conftest.py, we are creating a cluster that specifies both `worker_vm_type` and `worker_memory`, 
https://github.com/coiled/coiled-runtime/blob/d53473e6899968d5fb5d1837fa62d18828e7ac72/conftest.py#L74-L89
and this is causing us not to get the instances that we requested for the workers as it seems coiled infers the worker instances based on `worker_memory`. 
![Screen Shot 2022-06-02 at 3 25 07 PM](https://user-images.githubusercontent.com/7526622/171721529-9a0dc20e-c93d-4571-b923-c1d81bca1a20.png)

I filed the respective issue on coiled about this, as we should get an error or a warning mentioning this. But in the meantime I suggest we remove `worker_memory` in the `Cluster()`  call.

**Comment by ncclementi** [comment]
Looking at the pricing I see that t3.large are cheaper so maybe we want both the scheduler and the workers to use t3.large . Is there a reason why we would go for m5.large?

m5.large | 2 | 8 GiB | EBS only | $0.10 -> on demand hourly price

t3.large | 2 | 8 GiB | EBS only | $0.08  -> on demand hourly price

Link to pricing aws page: https://www.ec2pricing.net/

cc: @jrbourbeau @hayesgb @ntabris

**Comment by jrbourbeau** [comment]
Nice catch @ncclementi! 

>  I see that t3.large are cheaper so maybe we want both the scheduler and the workers to use t3.large . Is there a reason why we would go for m5.large?

It looks like there's not a huge price difference between these two instance types. Do you know what the default is that Coiled uses?

**Comment by ncclementi** [comment]
There is not a huge difference in price, but we are adding more and more tests, and cluster creations, so it wouldn't hurt going for the cheaper one unless there is a good reason not to. 

I just launched a cluster without specifying any instance type or worker memory and it looks like the default type is a

t3.medium | 2 | 4 GiB | EBS only | $0.04

**Comment by jrbourbeau** [comment]
Gotcha, thanks for checking. If `t3.large` or `m5.large` was the default, then it would be good motivation for choosing the default instance type. But since `t3.medium` is the default, it's less clear. Maybe we should just go with `t3.large` since, as you mentioned, it's cheaper. I don't know what other factors differentiate `t3.large` vs `m5.large`

**Comment by ncclementi** [comment]
Closing this, as https://github.com/coiled/coiled-runtime/pull/159 was merged, not sure why the autoclosing didn't work.
