### ISSUE TITLE
Shutdown code might not be working as expected. [BUG]

### ISSUE THREAD

**Issue by ncclementi** [coiled/coiled-runtime#158]
In the coiled dashboard, I'm seeing these clusters that have been up for a while not doing any work and the idle code is not closing them, even though the CI looks like passed with no problem. (Closing the clusters manually)

![Screen Shot 2022-06-02 at 3 57 13 PM](https://user-images.githubusercontent.com/7526622/171727321-498ccd92-32bb-49ec-8984-c5dc9799a985.png)

https://github.com/coiled/coiled-runtime/runs/6714230098?check_suite_focus=true
any idea what could it be?

Details pages:
https://cloud.coiled.io/dask-engineering/clusters/31051/details
https://cloud.coiled.io/dask-engineering/clusters/31122/details

**Comment by jrbourbeau** [comment]
I suspect they're running into the preload issue that https://github.com/dask/distributed/pull/6458 fixes. Updating to the latest `distributed` release (xref https://github.com/coiled/coiled-runtime/pull/149) should fix this

**Comment by jrbourbeau** [comment]
Closing as the 0.0.4 release is out and includes https://github.com/dask/distributed/pull/6458
