### ISSUE TITLE
Block coiled-runtime until verification of dask patch

### ISSUE THREAD

**Issue by hayesgb** [coiled/coiled-runtime#171]
Need to block next release of coiled-runtime until next dask release

**Comment by jrbourbeau** [comment]
Thanks @hayesgb -- this is already happening (xref https://github.com/coiled/coiled-runtime/pull/149). Just to be clear, do you mean the 2022.6.0 release happening later today?

**Comment by hayesgb** [comment]
The release today may be postponed.

**Comment by jrbourbeau** [comment]
My guess is the motivation for this is coming from some offline user report. If we've identified something that would block the Dask release, we should try to raise a public issue (if possible) and chime in on https://github.com/dask/community/issues/252 with reasoning behind why the release should be blocked

**Comment by ncclementi** [comment]
It seems we have a fix in progress, we should wait for this to be merged and include in a release? 
https://github.com/dask/distributed/pull/6562

**Comment by jrbourbeau** [comment]
@fjetter and chatted about this offline and decided we want to just set a lower bound for `openssl` in `coiled-runtime` instead of waiting for the next Dask release (scheduled for Friday next week) which will contain https://github.com/dask/distributed/pull/6562
