### ISSUE TITLE
Performance regression visibility 

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#190]
Today each CI run prints the time it took each test to run. Technically, this contains the information we need to identify a performance regression, but in practice such a regression is likely to go unnoticed as we don't regularly check the times printed in CI. As part of https://github.com/coiled/coiled-runtime/issues/148, it would be great to have CI automatically fail if there was a significant performance regression detected in our benchmarks.

**Comment by ncclementi** [comment]
Folks, writing a comment here as I'm behind on implementing this and I'm going on PTO until Tuesday 02/08. 

But at least we made progress on the design of this. After a meeting with James, we agreed that to start we just need something simple and that upon regression (whatever this means) we get an error raised. 
Tasks:
- [ ] Create a post-processing python script that compares the latest run with some statistics from n-previous runs. If fails, raise an error.
- [ ] Add step to GHA to run this before uploading it to the database. (still not clear whether we want to upload or not)
- [ ] The failure will trigger the report and open a CI fail.
