### ISSUE TITLE
Change to 0.x.0 releases so pinned versions can be updated

### ISSUE THREAD

**Issue by MrPowers** [coiled/coiled-runtime#194]
Right now, we're releasing versions like 0.0.3 and 0.0.4.

It just occurred to me that this will make it hard to deal with pinned versions that need to be updated.

For example, on another project, dependabot is telling me that I need to update numpy from 1.21.6 => 1.22 for a security vulnerability.  We may want to rerelease Coiled Runtime 3 with these changes.  I think we should change the numbering convention to be 0.3.0 instead of 0.0.3.  The new numbering convention would let us update the pinned version of Coiled Runtime 3 and release 0.3.1.

**Comment by ncclementi** [comment]
This is related to https://github.com/coiled/coiled-runtime/issues/133

There is clearly a decision to be made moving forward, and this makes sense.  I'm not sure we should go backward now with and change an existing version as some people are using it. 

@MrPowers Can you point to the vulnerability alert here so we have it as a reference? 

For your project, do you need to use 0.0.3 or would it be possible to use 0.0.4?

**Comment by MrPowers** [comment]
@ncclementi - here's the Dependabot alert for reference:

<img width="954" alt="Screen Shot 2022-06-25 at 9 44 21 AM" src="https://user-images.githubusercontent.com/2722395/175778579-2dbf66ae-7ddb-440c-b8d2-9a4e48c0d5a4.png">

Yea, don't think we should go backwards now, but perhaps we can make a 0.4.0 release that's identical to the 0.0.4 release and use the 0.x.0 release convention going forward?

**Comment by ncclementi** [comment]
Closing this as we have released 0.1.0.
