### ISSUE TITLE
Tooltip always show duration even in memory plots [dashboard]

### ISSUE THREAD

**Issue by ncclementi** [coiled/coiled-runtime#218]
Showing durations on tooltip when in memory tab: 

![Screen Shot 2022-07-28 at 7 59 29 PM](https://user-images.githubusercontent.com/7526622/181656343-b91a0e1f-a2b3-4583-92ab-4989d643857c.png)

I'm pretty sure this comes from how the tooltip is created, see here https://github.com/coiled/coiled-runtime/blob/fb3a04f91581c2582c520b30006f63cd0055f156/dashboard.py#L80 . I think that line should be something like 

```python
altair.Tooltip(f"{spec.field}:Q", title=spec.label), 
```
I tried this change and the only caveat is that instead of saying durations now it'll say Wall Clock, for the Wall clock part.  

with the proposed change : 

![Screen Shot 2022-07-28 at 8 14 14 PM](https://user-images.githubusercontent.com/7526622/181657602-25f48a1d-5928-426d-a3e5-9733237f6993.png)
![Screen Shot 2022-07-28 at 8 15 32 PM](https://user-images.githubusercontent.com/7526622/181657698-d906cf98-89b2-4933-99c5-37e87eca225c.png)

cc: @ian-r-rose

**Comment by ian-r-rose** [comment]
We could also just put more fields in the tooltip. We aren't really constrained by anything there except if the tooltips get really long and difficult to read. But your fix is fine, as well!
