### ISSUE TITLE
Unable to import `coiled` when installing `coiled-runtime` from pip

### ISSUE THREAD

**Issue by scharlottej13** [coiled/coiled-runtime#231]
I was testing using pip to install `coiled-runtime` and was having some problems importing `coiled`. I'm not the most familiar with pip, so not quite sure the best way to troubleshoot. Here's what I did:

```
python3 -m venv test
source test/bin/activate
python3 -m pip install coiled-runtime
```

Then, in a python session when I try to import coiled I get a `ModuleNotFoundError`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'coiled'
```

This is python version 3.9, pip 22.2.2, and coiled-runtime 0.0.1 (the only version I saw on PyPI).

**Comment by ntabris** [comment]
https://github.com/coiled/coiled-runtime/issues/153#issuecomment-1198829177

**Comment by ntabris** [comment]
@jrbourbeau what's the status of getting a real coiled-runtime release on pypi? @scharlottej13 is in the process of updating docs to tell people they can install from conda-forge OR pypi.

**Comment by scharlottej13** [comment]
> [#153 (comment)](https://github.com/coiled/coiled-runtime/issues/153#issuecomment-1198829177)

Wow I'm so sorry I completely missed that! I just got really excited to try it out! 😬

**Comment by jrbourbeau** [comment]
See https://github.com/coiled/coiled-runtime/issues/233

**Comment by scharlottej13** [comment]
Thank you @jrbourbeau! I think I can close this issue too.
