### ISSUE TITLE
Use `boa` for recipe building 

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#24]
We should investigate using `boa` (from the `mamba` folks) for building conda recipes instead of `conda-build`. `boa` has a few nice features including using `mamba` for solves instead of `conda` (see https://boa-build.readthedocs.io/en/latest/mambabuild.html).

**Comment by ncclementi** [comment]
We did in the past, and got problems on the windows py38 hence we defaulted back to conda. 
This was the commit https://github.com/coiled/coiled-runtime/pull/1/commits/3ee65afc047ecd2a0fdd2ca7c26d71691cf03020

this was the failure https://github.com/coiled/coiled-runtime/runs/5397860740?check_suite_focus=true

**Comment by jrbourbeau** [comment]
Ah, thanks for the additional context @ncclementi. I might push up a quick PR to see if that's still and issue or not.
