### ISSUE TITLE
Consider adding `pynvml` for GPU usage support

### ISSUE THREAD

**Issue by phobson** [coiled/coiled-runtime#255]
A coiled-runtime user (@arnaudsj) reported that they were unable to track their GPU usage in the dashboard. @ntabris figured out that their software environment (based on the coiled-runtime IIUC), was missing `pynvml`. 

Is it possible to add this to the coiled-runtime?

From what I can tell, including it won't meaningfully pull in additional dependencies:

It [requires](https://github.com/gpuopenanalytics/pynvml/blob/master/requirements.txt): 
- pip>=9.0.1
- pytest>=3.6,<7.0
- pytest-runner
- pytest-cov

**Comment by ntabris** [comment]
I don't see any downside to this. `pynvml` is small, not platform/arch specific, and on both conda-forge and pypi.

**Comment by jrbourbeau** [comment]
Closed via https://github.com/coiled/coiled-runtime/pull/264
