### ISSUE TITLE
`distributed=2022.6.0` used by `v0.1.0` contains regression

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/coiled-runtime#306]
In `distributed=2022.6.0`, a regression was introduced (https://github.com/dask/distributed/issues/6624) that causes issues with `map_overlap`. This regression has been fixed in `2022.6.1` (https://github.com/dask/community/issues/258#issuecomment-1165546771). I suggest a new minor release of `coiled-runtime` that bumps the version of `dask` and `distributed`.

XREF: This causes a newly created test for #305 to fail.

**Comment by ncclementi** [comment]
Closing this as we are planning on releasing 0.2.0 soon.
