### ISSUE TITLE
test_basic_sum occasionally takes 340% time and 160% memory to complete

### ISSUE THREAD

**Issue by crusaderky** [coiled/coiled-runtime#315]
`benchmarks/test_array.py::test_basic_sum` usually runs in \~80s wall clock time, \~21GiB average memory, and 27\~33GiB peak memory.
Once in a while, however, it takes \~270s wall clock time, 32\~35GiB average memory, and \~46GiB peak memory.
Both sets of measures are internally very consistent - it's almost exactly always one or the other.

I can't imagine what could possibly happen to trigger a "bad" run.
Both the test and the algorithm being tested are extremely simple. 
Time measures start when all workers are up and running and stop before shutting them down.
There should not be any spilling involved; network transfers should be very mild.
Even in the event of a CPU and/or network slowdown, there should not be an increase in memory usage.

Screenshots from coiled 0.1.0 (dask 2022.6.0), but I've observed the same behaviour on 2022.8.1 as well:

![Screenshot from 2022-09-08 11-01-02](https://user-images.githubusercontent.com/6213168/189095904-e7e563af-0ecb-4227-9935-7396c76bd9e6.png)
![Screenshot from 2022-09-08 11-04-50](https://user-images.githubusercontent.com/6213168/189096135-93c2b9b4-67ed-41dc-b9fd-2226ca5207d6.png)
![Screenshot from 2022-09-08 11-01-15](https://user-images.githubusercontent.com/6213168/189096154-a7439f2c-5fbe-4f52-874f-b4a6a0b8bb40.png)

**Comment by fjetter** [comment]
very interesting.
as with most things lately I’m typically asking if this is reproducible without work stealing.

Have you tried reproducing it? Just by counting it looks like ~5% of all runs are affected (assuming there is no infrastructure issue)

**Comment by crusaderky** [comment]
> Have you tried reproducing it? 

Not yet

**Comment by fjetter** [comment]
If stealing is not the culprit, my next guess would be reevaluate_occupancy which recomputes occupancies on a round robin basis but may be skipped if CPU load on the scheduler is too high. See also https://github.com/dask/distributed/issues/6573#issuecomment-1239413543

At this point this is merely guessing about non-deterministic parts of our scheduling logic

**Comment by ntabris** [comment]
Slow `test_basic_sum`: https://github.com/coiled/coiled-runtime/runs/8245244815?check_suite_focus=true#step:6:179

Fast `test_basic_sum`: https://github.com/coiled/coiled-runtime/runs/8218741702?check_suite_focus=true#step:6:190

Do we have a way to find the clusters these ran on? Or other data about these runs beyond just the wall-clock times?

**Comment by ian-r-rose** [comment]
> So short answer to both is no. (We have peak and avg memory use as well as wall-clock time, but in general nothing with more granularity.)

This is mostly true, but note that we are also tracking compute, transfer, and disk-spill time, it's just not visualized at the moment. So if the compute time stayed roughly constant while the wall clock time spiked, I would suspect something went wrong with scheduling.

**Comment by fjetter** [comment]
FYI @hendrikmakait got his hands on a performance report of a slow run.

the task stream shows wide white gaps and we see that the scheduler event loop is stuck for a while (one time up to ~46s). No GC warnings. Not sure but highly suspect this aligns with the white gaps.

There are a couple of "Connection from tls://77.20.250.112:30608 closed before handshake completed" messages following this 46s tick. I suspect this is a heartbeat? Can't find any corresponding logs on any of the workers.
The IP range is a bit funny since all registered workers are using a 10.X.X.X IP

It happened on https://cloud.coiled.io/dask-engineering/clusters/68284/details

[cloudwatch logs](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E$25272022-09-13T08*3a36*3a21.000Z$257Estart$257E$25272022-09-13T04*3a08*3a48.000Z$257EtimeType$257E$2527ABSOLUTE$257Etz$257E$2527Local$257EeditorString$257E$2527fields*20*40timestamp*2c*20*40message*0a*7c*20filter*20*28*40logStream*20like*20*2ftest_array-da25a4ce*2f*20and*20*40message*20like*20*2fdistributed*5c.*2f*29*0a*7c*20sort*20*40timestamp*20asc*0a$257EisLiveTail$257Efalse$257EqueryId$257E$2527efb12e6b-a629-454e-a392-4ba7047b58e2$257Esource$257E$2528$257E$2527dask-engineering$2529$2529$26tab$3Dlogs)

@ntabris do you know why we're seeing different IP addresses here? Should this concern us?

**Comment by ntabris** [comment]
77.20.250.112 is Vodafone Germany, so presumably client IP.

I'll take a look at the logs later this morning and see if I can make anything of them.

**Comment by fjetter** [comment]
> I'll take a look at the logs later this morning and see if I can make anything of them.

Thanks. That should already help clear things up. I don't think you'll find anything useful in the logs. I think this is our problem ;)

**Comment by fjetter** [comment]
If the above are client side connection attempts, this may be related to us trying to fetch performance reports, etc. If nothing failed client side, I suspect smth like `Client._update_scheduler_info` ot be causing this

**Comment by crusaderky** [comment]
> the task stream shows wide white gaps and we see that the scheduler event loop is stuck for a while (one time up to ~46s). No GC warnings. Not sure but highly suspect this aligns with the white gaps.

Do we have a measure of CPU seconds of the scheduler process?
- The whole VM could be temporarily frozen; if that were the case you'd have e.g. 46s wall time 0.1s CPU time. 
- Another thing to investigate is the user/sys CPU split. A very high sys CPU time could again highlight something wrong at VM level

**Comment by hendrikmakait** [comment]
While root-causing #316, we have discovered a bug in `scaled_array_shape` which likely affects `test_basic_sum` as well.

**Comment by gjoseph92** [comment]
Looks like it's not a bug in `scaled_array_shape`, but rather in `dask.array.core.normalize_chunks`. For certain `shape` arguments, it will return chunk sizes that are wildly different from the requested chunk size, but if the shape is 1 larger or smaller, it will do as requested.

I'm looking into it and will open an issue over there.

**Comment by gjoseph92** [comment]
- https://github.com/dask/dask/issues/9488

Not clear if this is the _only_ thing causing the variation, but it's certainly not helping.

**Comment by crusaderky** [comment]
![Screenshot from 2022-10-20 01-49-36](https://user-images.githubusercontent.com/6213168/196831097-033d9d51-1db8-4a20-939e-770cc8a435db.png)

From the raw db dump I think I'm reading that, in the "bad" runs, there are many many more network transfers (`transfer_time`) than in the "good" ones and substantially more memory duplication - which in turn causes spilling (`spill_time`).

It looks like co-assignment is occasionally and randomly falling apart for some reason?
Progressing further with investigation.

**Comment by crusaderky** [comment]
Holy work stealing Batman!
There are 643 ready->released worker transitions in the good run, vs. 6419 ones in the bad one.
For scale, there are 4921 tasks in total.

In the good run, 13% of the tasks end up stolen (it feels quite high already).
In the bad run, each task is stolen 1.3 times on average!

| start | recs | end | bad | good | delta | 
| --- | --- | --- | --- | --- | --- | 
| cancelled | memory | released | 19 | 3 | 16 | 
| executing | memory | memory | 4922 | 4921 | 1 | 
| fetch | flight | flight | 2087 | 205 | 1882 | 
| fetch | released | released | 15 | 0 | 15 | 
| flight | memory | memory | 2068 | 202 | 1866 | 
| flight | released | cancelled | 19 | 3 | 16 | 
| memory | released | released | 6990 | 5123 | 1867 | 
| ready | executing | executing | 4922 | 4921 | 1 | 
| ready | released | released | 6419 | 643 | 5776 | 
| released | fetch | fetch | 2102 | 205 | 1897 | 
| released | forgotten | forgotten | 13466 | 5772 | 7694 | 
| released | waiting | waiting | 11364 | 5567 | 5797 | 
| waiting | ready | ready | 11341 | 5564 | 5777 | 
| waiting | released | released | 23 | 3 | 20 | 

> Can we see if a worker has left at any point? 

No workers left.

>  is it possible the initial task assignment happens before all workers have arrived?

No, I see that the first task transition is 2 seconds after the last worker joined the cluster.

**Comment by crusaderky** [comment]
It looks like work stealing stole equally from all workers - thus obtaining a net zero rebalancing effect!

Number of tasks lost to work stealing:
![image](https://user-images.githubusercontent.com/6213168/197080407-04c08260-477c-4d45-9c73-fe357693a090.png)
![visualization](https://user-images.githubusercontent.com/6213168/197081109-96fb158e-4c19-4eda-8dfa-eda760715d87.png)

**Comment by crusaderky** [comment]
Task durations.
The first, fast one on the top left is the most important one, as it is the first aggregation layer (3688 tasks).
The second layer is 923 tasks, the third is 1/4th of the third, and so on.

![visualization (1)](https://user-images.githubusercontent.com/6213168/197084368-48a5712e-e4b5-4c5c-94b7-29ec2c12c113.png)

It's interesting to see here how the bad run, which is spilling a lot more, has much longer "flares" of outliers. Those are all moments where the event loop of the worker was busy spilling; this impacted the measured duration, which in turn *might* have caused improper stealing choices.
However poor stealing decisions started much before the worker started spilling, so I don't think this is the cause.

**Comment by crusaderky** [comment]
I'm looking now at coiled-upstream (dask 2022.08.0 ~ 2022.10.0) vs. coiled-latest (2022.6.0) and coiled-0.1.0 (2022.6.0) and the noise is completely gone in the newer releases.
So I'm inclined to close this issue without further investigation.

upstream
![download](https://user-images.githubusercontent.com/6213168/197181038-edcae402-6aa8-415a-9054-d24ac896ec4b.png)

latest
![download (1)](https://user-images.githubusercontent.com/6213168/197181089-0d3a18a9-bfb1-4df3-8898-d375b5b302ab.png)

0.1.0
![download (2)](https://user-images.githubusercontent.com/6213168/197181115-9ba96d84-5e2c-4879-9c5e-0990ce1668f7.png)

**Comment by hendrikmakait** [comment]
> I'm looking now at coiled-upstream (dask 2022.08.0 ~ 2022.10.0) vs. coiled-latest (2022.6.0) and coiled-0.1.0 (2022.6.0) and the noise is completely gone in the newer releases. So I'm inclined to close this issue without further investigation.

Good to see that the recent changes to work-stealing seem to have removed the erratic behavior. Some of the issues that were fixed (including work-stealing going overboard and stealing way too much) could explain the behavior that has been observed.
