### ISSUE TITLE
`Wall Clock (s)` spikes for `benchmarks/test_array.py::test_double_diff` without CI failure

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/coiled-runtime#316]
We had a significant spike in `Wall Clock (s)` for `benchmarks/test_array.py::test_double_diff` but did not receive an alert. 

<img width="821" alt="Wall Clock (s) spiked" src="https://user-images.githubusercontent.com/2699097/189371524-5443871d-2782-4a4a-850e-d99b1fd89b47.png">

At the same time, `Average Memory (GiB)` dropped, which might suggest recent data transfer limiting to be the cause.
<img width="829" alt="Average Memory (GiB) dropped" src="https://user-images.githubusercontent.com/2699097/189371867-df76802d-fcc2-49a3-9955-f442a5ae4f49.png">

https://coiled.github.io/coiled-runtime/coiled-upstream-py3.9.html

I am investigating further.

**Comment by hendrikmakait** [comment]
The suspicious run uses https://github.com/dask/dask/commit/5f11ba94cd5b1e0284c5246c4583e3a898d6447d and https://github.com/dask/distributed/commit/f02d2f91f16ca48b453907352dcf92789a492dab. 
The run before it uses https://github.com/dask/dask/commit/e74888aae1faa72a5ce18ccc1cfaaf7dee2093ea and https://github.com/dask/distributed/commit/c7d5ba7a0321d2fd71b42bbdff3021ba3fa7d3ce.

After benchmarking`test_double_diff` several times from my local machine comparing `2022.9.0` against the latest `main`, I have not been able to find anything suspicious. The numbers for both versions are comparable around 120s.

I suggest revisiting the benchmarking results on Monday to check whether this issue remains. cc @fjetter

**Comment by hendrikmakait** [comment]
**Update**

Over the weekend, the wall time has been highly variable: 
<img width="828" alt="Wall Clock (s) has been highly variable" src="https://user-images.githubusercontent.com/2699097/189602658-99b3d7ec-5626-4be3-b5de-aca68308ed74.png">

I'm not sure what to make of this. We have seen a somewhat similar spike, though less pronounced, around 08/31.

**Comment by fjetter** [comment]
Just ran this on 2022.6.0 and got a runtime of ~110s

This run already looks a bit suspicious with a couple of idling workers in the middle. I bet that this looks drastically different on one of the spikes

For reference

![image](https://user-images.githubusercontent.com/8629629/189618133-06c8fd03-3e43-49aa-b242-6671863ef09a.png)

It's interesting that this workload already stresses out the scheduler

![image](https://user-images.githubusercontent.com/8629629/189619124-e786a86f-5745-4f69-a1d7-23fbf01e4efb.png)


[perf-report-compressed.html.tar.gz](https://github.com/coiled/coiled-runtime/files/9546610/perf-report-compressed.html.tar.gz)

**Comment by ncclementi** [comment]
Cross-referencing this here https://github.com/coiled/coiled-runtime/issues/299

@hendrikmakait the reason why we haven't got an alert is that in main we check if the last 3 runs are bigger than (mean + 2std) of the latest 10 values not-including the 3 we are looking at. 

Since this test is super noisy, I'm expecting this kind of behavior. 

That being said I reported seeing this in #299 but there was no followup.

**Comment by ntabris** [comment]
FYI you should be able to get 1s interval cpu/mem metrics on staging now. I'm starting to look at these myself in grafana and would be happy to do this w/ someone on a call.

**Comment by ntabris** [comment]
I did 10 runs of double_diff, same cluster w/ `client.restart` between each test, scheduler was `t3.xlarge`, 10 `t3.large` workers.

Some runs were ~130s, some were >200s.

```
2022-09-13 10:20:47,186 - double_diff - INFO - Starting test run 0 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:23:35,371 - double_diff - INFO - Test run 0 took 168.18530666595325 seconds

2022-09-13 10:23:48,736 - double_diff - INFO - Starting test run 1 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:26:03,423 - double_diff - INFO - Test run 1 took 134.6871834998019 seconds

2022-09-13 10:26:16,248 - double_diff - INFO - Starting test run 2 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:28:35,412 - double_diff - INFO - Test run 2 took 139.16386704239994 seconds

2022-09-13 10:28:48,304 - double_diff - INFO - Starting test run 3 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:31:07,336 - double_diff - INFO - Test run 3 took 139.03207729198039 seconds

2022-09-13 10:31:19,935 - double_diff - INFO - Starting test run 4 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:35:37,806 - double_diff - INFO - Test run 4 took 257.87163662491366 seconds

2022-09-13 10:35:50,653 - double_diff - INFO - Starting test run 5 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:37:49,975 - double_diff - INFO - Test run 5 took 119.32307670917362 seconds

2022-09-13 10:38:02,997 - double_diff - INFO - Starting test run 6 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:41:40,731 - double_diff - INFO - Test run 6 took 217.73480700002983 seconds

2022-09-13 10:41:53,458 - double_diff - INFO - Starting test run 7 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:45:47,499 - double_diff - INFO - Test run 7 took 234.04223141726106 seconds

2022-09-13 10:46:00,465 - double_diff - INFO - Starting test run 8 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:48:26,480 - double_diff - INFO - Test run 8 took 146.01530083315447 seconds

2022-09-13 10:48:39,064 - double_diff - INFO - Starting test run 9 on cluster double-diff-4bf298ef
Cluster memory: 71.46 GiB, target data size: 71.46 GiB
Input 1: 71.46 GiB - 3721 20.00 MiB chunks
Input 2: 71.46 GiB - 3721 20.00 MiB chunks
2022-09-13 10:51:26,785 - double_diff - INFO - Test run 9 took 167.72131154080853 seconds

```

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/46289310/189968266-5914ce3a-2d05-4747-abc2-8c2a88a72142.png">

**Comment by ntabris** [comment]
Logs for scheduler and the worker blocked on IO for my 10 runs:

[double-diff-4bf298ef-scheduler-523f5517d5-instance.txt](https://github.com/coiled/coiled-runtime/files/9559571/double-diff-4bf298ef-scheduler-523f5517d5-instance.txt)

[double-diff-4bf298ef-worker-8809d332d3-instance.txt](https://github.com/coiled/coiled-runtime/files/9559572/double-diff-4bf298ef-worker-8809d332d3-instance.txt)

**Comment by hendrikmakait** [comment]
After diving into the logs, it looks like the worker event loop gets unresponsive while spilling. For example, take a look at the last annotated run on the Grafana dashboard between 16:39:00 UTC and 16:42:00: 
_Worker logs_
```
Sep 13 16:39:53 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:39:53,499 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.72s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Sep 13 16:39:56 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:39:56,601 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.10s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Sep 13 16:40:02 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:40:02,809 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.94s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Sep 13 16:40:24 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:40:24,838 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.45s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Sep 13 16:40:29 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:40:29,285 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.61s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Sep 13 16:40:52 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:40:52,322 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.65s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Sep 13 16:40:56 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:40:56,971 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.65s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Sep 13 16:41:04 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:41:04,049 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.17s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Sep 13 16:41:09 ip-10-6-55-39 cloud-init[1050]: 2022-09-13 16:41:09,489 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.96s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
```

**Comment by gjoseph92** [comment]
> it looks like the worker event loop gets unresponsive while spilling

This is currently expected, but known to be problematic: https://github.com/dask/distributed/issues/4424

**Comment by hendrikmakait** [comment]
> This is currently expected, but known to be problematic: https://github.com/dask/distributed/issues/4424

Yeah, I think https://github.com/dask/distributed/issues/4424 and the general fact that we're spilling so much might be some causes of the problem we see here.

**Comment by fjetter** [comment]
If a worker is blocked by IO while spilling/unspilling an important task that frees up parallelism that would also explain why we're seeing gaps in the task stream, i.e. the scheduler event loop block may be yet another red herring (but also smth to investigate since it definitely could cause a similar problem; at the very least task overproduction)

**Comment by ntabris** [comment]
I'm pretty convinced from the hardware metrics that IO blocking consistently explains the difference in test time. For example, I just ran another batch of `double_diff` test this morning, here's comparison between faster and slower run:

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/46289310/190158235-cfcdc72a-d3e5-4909-b3fe-dc5819c586ba.png">

Here are a couple other individual test runs where I annotated start of test (single line) and scheduler event loop being blocked (range). The annotation points aren't exact since I have 5s granularity, but it's enough to see that scheduler event loop is blocked near beginning of test, right around the time that worker CPU jumps up and when scheduler starts receiving messages:

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/46289310/190159273-7c88046f-cc39-4629-bdde-653d41628b98.png">

(For reference, I'm using `t3.xlarge` scheduler which has 2 physical cores, 4 "vCPUs".)

**Comment by gjoseph92** [comment]
> The scheduler event loop pretty consistently is becoming unresponsive at the start of each `double_diff` test, but it's also pretty consistently ~10s

I'd guess that's [`dask.order`](https://github.com/gjoseph92/distributed/blob/f3de3b95c7d13f9f2e35eae6592c6b608053d3f6/distributed/scheduler.py#L4327) primarily, which blocks the event loop. Also deserialization, and creating and scheduling of the initial tasks.

When profiling the scheduler, it's common to see receiving the graph take a nontrivial amount of the total runtime, nearly all with the event loop blocked.

**Comment by hendrikmakait** [comment]
After the changes in #328, I have not seen any major differences in runtime of `test_double_diff` except for an initial delay before the cluster starts becoming busy which is likely due to issues with the client-scheduler connections, which spans the Atlantic Ocean in my case. It is also worth noting that the major discrepancies observed by @ntabris in https://github.com/coiled/coiled-runtime/issues/316#issuecomment-1246724981 were using `coiled-runtime==0.10` which already shows a pretty wild behavior on CI. With the latest master I was only able to observe minor influences of spilling onto the runtime of the tests. I suggest we monitor the CI behavior now that #328 has been merged and close this issue if that's the case.

**Comment by ntabris** [comment]
I also just ran the test 5 times on dask/distributed 2022.9.0 (t3.xlarge scheduler, 10 t3.large workers).

Test times were lower and consistent (103–105s), spill was significantly lower:

<img width="2482" alt="image" src="https://user-images.githubusercontent.com/46289310/190242388-99c99bb1-38a6-441e-8da7-06988d9ab94c.png">

**Comment by hendrikmakait** [comment]
The latest two runs look pretty good, closing this for now.

<img width="828" alt="Improved wall clock time for test_double_diff" src="https://user-images.githubusercontent.com/2699097/190589293-b91df881-f2c4-42d7-9f21-ab5b6f6519ed.png">
