### ISSUE TITLE
Create GHA workflow for managing Coiled software environments

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#32]
As we start testing `coiled-runtime` on Coiled clusters, we'll need to have Coiled software environments with various versions of `coiled-runtime` installed. We should create a GHA workflow which manages these software environments. This workflow should be separate from our existing workflows that run on PRs to avoid software environments being unintentionally changed when someone is working on a PR

**Comment by dchudz** [comment]
Question:

The job that updates software environments will need to run at least as often as e.g. the quickstart test (https://github.com/coiled/coiled-runtime/pull/31), right?

If I understand this right, you'd need to update the software environment in order to actually be testing the intended code.

**Comment by jrbourbeau** [comment]
> what versioning scheme are you thinking of for the coiled-runtime? Semantic?

Great question. I believe semantic is what we're using. cc @hayesgb as he was involved in conversations around this 

> The job that updates software environments will need to run at least as often as e.g. the quickstart test (https://github.com/coiled/coiled-runtime/pull/31), right?

Hmm I don't quite follow. It's not clear to me why we would need to update the Coiled software environments each time we runs the test suite. Could you elaborate a bit more on this point?

**Comment by dchudz** [comment]
> It's not clear to me why we would need to update the Coiled software environments each time we runs the test suite. Could you elaborate a bit more on this point?

I guess I should have started with a question: What is a test like https://github.com/coiled/coiled-runtime/pull/31 meant to test?

Maybe I'm confused about the goals and/or how this is put together. (If so, sorry! Maybe you can help me see it.) I had assumed the test had a goal of testing that a dask Cluster, created with Coiled, (with versions in the coiled-runtime) can perform a computation on the nyc taxi dataset.

Since this test launches a cluster using the (pre-existing) `dask-engineering/coiled_dist-py{sys.version_info[0]}{sys.version_info[1]}` software environment, it won't have a cluster that reflects any any changes to `coiled-runtime`, unless a new software environment is created.

**Comment by dchudz** [comment]
In other words:

I would expect that your goal is exercise the version of the code (yaml file) that's under test. To do that in Coiled, you need a software environment (or need some other way to install the relevant packages on the cluster).

**Comment by jrbourbeau** [comment]
> Maybe I'm confused about the goals and/or how this is put together

No worries at all. To be clear, this is still under construction! Feedback is actively encouraged

> I had assumed the test had a goal of testing that a dask Cluster, created with Coiled, (with versions in the coiled-runtime) can perform a computation on the nyc taxi dataset.

That's correct -- that's the goal of that test. We want to make sure that, when using `coiled-runtime`, the Coiled quickstart works. 

You're getting at an important point that we haven't solved yet which is there are a _multiple_ versions of `coiled-runtime` we want to test against. For example, whatever released versions that are supported -- today we only have 0.0.3 out, but in the future we might support 1.1.1, 1.1.2, 1.1.3 (just making those versions up). We also want to test against the current `coiled-runtime` that's defined in this repository, but unreleased (right now I'm referring to this as the "latest" `coiled-runtime` version). 

Testing against released versions of `coiled-runtime` is _relatively_ easy as we can just use a static conda env file (and corresponding Coiled software environment which we build once). Testing against the "latest" `coiled-runtime` is more difficult because, to your point, we need to build whatever is in this repo. Today we're being sloppy and building/installing the latest `coiled-runtime` in the GHA CI environment 

https://github.com/coiled/coiled-runtime/blob/65514010128ac5edd291c42601225ae71968e223/.github/workflows/conda.yml#L44-L55

but still using a Coiled software environment that has `coiled-runtime=0.0.3` installed in it. This works today because we haven't changed any of the version pinning in this repo since releasing 0.0.3, but things will start to fail once we update those pinnings. 

So yeah, I see your point now. Hopefully this, very long, comment gives a better state of where things are today and where we want them to go

**Comment by dchudz** [comment]
Right.

And it's not necessarily just what's in `main` of the repo.

I guess https://github.com/coiled/coiled-runtime/pull/31 doesn't run on PRs for now, but if you ever have tests like that which do, then they'll only be testing the right thing if you make a new senv for the PR.

**Comment by jrbourbeau** [comment]
> I guess https://github.com/coiled/coiled-runtime/pull/31 doesn't run on PRs for now

https://github.com/coiled/coiled-runtime/pull/31 (along with the rest of the tests in the `tests` directory) should be running on PRs and pushes to `main`. 

> they'll only be testing the right thing if you make a new senv for the PR

That's correct -- this is something we'll need to add

**Comment by dchudz** [comment]
Cool. Nothing wrong with WIP. :-)

**Comment by jrbourbeau** [comment]
I opened https://github.com/coiled/coiled-runtime/pull/27 yesterday, which isn't a complete solution, but is moving in the right direction

**Comment by jrbourbeau** [comment]
With automatically creating Coiled software environments for the latest `coiled-runtime` on PRs / pushes to `main` taken care of in https://github.com/coiled/coiled-runtime/pull/33, I'd like to add more detail on managing Coiled software environments for _released_ versions of `coiled-runtime`. 

One potential approach would be to add a new top-level `env/` directory where we keep a conda environment file for each Coiled software env we maintain. Something with a file structure like:

```
coiled-runtime/
    env/
        coiled-runtime-0.0.3-py38.yaml
        coiled-runtime-0.0.3-py39.yaml
        coiled-runtime-0.0.3-py310.yaml
        coiled-runtime-0.0.4-py38.yaml
        coiled-runtime-0.0.4-py39.yaml
        coiled-runtime-0.0.4-py310.yaml
    ...
```

We then add a new GHA workflow, which only runs on pushes to `main` / workflow dispatching where we go through each of those environment yaml files and build the corresponding software environment.

**Comment by dchudz** [comment]
Some more thoughts/questions on this:

It sounds like you're planning for your team to manage the user-facing Coiled software environments? (That sounds good to me, but I wanted to clarify since it's somewhat of a boundary area between our teams.

- If yes: Would you plan to manage both specific named `coiled-runtime-...` envs, and the default environments (which are currently managed [here](https://github.com/coiled/software-environments)?

Version naming: I'm wondering how granular the version naming should get. I would assume that major (or even minor?) versions of the coiled runtime are stable enough that a bump from 0.0.3 to 0.0.4 does not require a user to upgrade their local versions. Is that right?

- If yes: Then maybe it would be better to use coarser names, so that I user on `coiled/coiled-runtime-0` gets the benefit of bugfixes without having to point to a new software environment.

**Comment by jrbourbeau** [comment]
> It sounds like you're planning for your team to manage the user-facing Coiled software environments? (That sounds good to me, but I wanted to clarify since it's somewhat of a boundary area between our teams.

I think this will be a good place for the platform and OSS teams to collaborate. But yes, the OSS team can own managing the runtime-related Coiled software environments.

> Would you plan to manage both specific named coiled-runtime-... envs, and the default environments (which are currently managed [here](https://github.com/coiled/software-environments)?

With the changes in https://github.com/coiled/software-environments/pull/64, it seems the runtime and default software environments are redundant. We might be able to consolidate

> Version naming: I'm wondering how granular the version naming should get. I would assume that major (or even minor?) versions of the coiled runtime are stable enough that a bump from 0.0.3 to 0.0.4 does not require a user to upgrade their local versions. Is that right?

Great question. This is something folks are actively thinking about. What would you like to see?

**Comment by dchudz** [comment]
> What would you like to see?

Mainly I'd like to see us "work backwords" from the user flows we want to support.

That's the high-level, but I do also have suspicions about what that'll mean. For example maybe:

- I'd like it to be true that if you upgrade the coiled-runtime used by a cluster in a patch-numbered version bump (0.0.5 to 0.0.6), everything will keep working even if you don't upgrade the client. (I.e., the mismatches created by that are not a problem.)
- I'd like users to be able to benefit from dask bugfixes without any client changes when possible.

I think those two items imply the patch number wouldn't be in the software environment.

I might say the same about the minor version even.

But maybe I'm making some wrong assumptions. I'm assuming that coiled-runtime is extremely stable at the "patch" or "minor version" level.

Other platform team folks probably have thoughts too, and may disagree with me. I'd love if you could write up a plan/proposal of whatever you're thinking and share it all of us!
