### ISSUE TITLE
spill test running out of disk space

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#320]
I've noticed that spill test is not infrequently getting `OSError(28, 'No space left on device')`.

Here are most recent 100 instances:

[no-space-exception.csv](https://github.com/coiled/coiled-runtime/files/9549556/no-space-exception.csv)

Maybe two issues here:

1. Adjust test so it doesn't run out of disk space (since I don't think this is intended)
2. Better detection for this error / relevant exceptions that occur during test runs

**Comment by ntabris** [comment]
cc @hendrikmakait @ian-r-rose

**Comment by ian-r-rose** [comment]
Over in #235 I adjusted the numbers on this test to make it rather less stressful and time consuming (as it stands, it's a huge fraction of the total test suite runtime).

**Comment by hendrikmakait** [comment]
It looks like the changes in #235 might have taken care of this.
<img width="828" alt="Screenshot 2022-09-16 at 14 22 39" src="https://user-images.githubusercontent.com/2699097/190637868-01a57bea-0bf5-4049-8ed8-523de6dfa3ea.png">
