### ISSUE TITLE
bump up scheduler vm size

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#332]
Lots of test use cluster with `t3.large` scheduler. This has 2 vCPUs, which in this case means single physical core. I strongly recommend using `t3.xlarge` instead, this will reduce potential contention between dask and system + monitoring agents.

(That said, it will also affect your longitudinal comparisons.)

**Comment by ncclementi** [comment]
@ian-r-rose If I recall correctly, you run some tests changing the size of the instances. Do you have any comments regarding this?

**Comment by fjetter** [comment]
+1

**Comment by ian-r-rose** [comment]
I have no objections to bumping to `t3.xlarge` schedulers. Should we also bump workers to t3.xlarge as well? It would probably mean just declaring bankruptcy on the whole test history, so if we wanted to do that we could also chat about any repo restructuring as well.

**Comment by fjetter** [comment]
I think we should keep the workers as is. bumping worker sizes will double our money spent and just shifts the scale of our benchmarks. The scheduler as a central bottleneck will benefit from a larger instance much more and will make our benchmarks less susceptible to whatever we're deploying next to the scheduler (e.g. monitoring as nat suggests)
