### ISSUE TITLE
`test_work_stealing_on_scaling_up` failing

### ISSUE THREAD

**Issue by ian-r-rose** [coiled/coiled-runtime#336]
#308 was merged a few days ago. It appears to be skipped for `2022.6.0` (cf #306), but it runs on upstream.
I have seen it fail a number of times with killed workers:

 https://github.com/coiled/coiled-runtime/actions/runs/3062687464/jobs/4943938999
https://github.com/coiled/coiled-runtime/actions/runs/3062426988/jobs/4943389537

We may want to skip it for the time being. cc @hendrikmakait

**Comment by fjetter** [comment]
I'd like to point out that this is not a flakiness problem but there appears to be a problem with the software environments

```
  +-------------+-----------------------+-----------+----------+
  | Package     | client                | scheduler | workers  |
  +-------------+-----------------------+-----------+----------+
  | dask        | 2022.9.0+22.g982376ef | 2022.6.0  | 2022.6.0 |
  | distributed | 2022.9.0+13.g1fd07f03 | 2022.6.0  | 2022.6.0 |
  +-------------+-----------------------+-----------+----------+
```

Did this fail before package_sync as well? The CI jobs you are pointing to are using package_sync.

**Comment by fjetter** [comment]
This test is using `cluster.scale` to upscale an existing cluster. @shughes-uk is this supported with package sync?

**Comment by hendrikmakait** [comment]
Note that the mismatch on [this cluster](https://cloud.coiled.io/dask-engineering/clusters/71815/details) looks somewhat different, but boils down to the same problem:
```
Sep 16 00:34:42 ip-10-0-11-96 cloud-init[1125]: +-------------+-------------+-----------+---------------------------------------+
Sep 16 00:34:42 ip-10-0-11-96 cloud-init[1125]: | Package     | This Worker | scheduler | workers                               |
Sep 16 00:34:42 ip-10-0-11-96 cloud-init[1125]: +-------------+-------------+-----------+---------------------------------------+
Sep 16 00:34:42 ip-10-0-11-96 cloud-init[1125]: | dask        | 2022.6.0    | 2022.6.0  | {'2022.6.0', '2022.9.0+25.g1a8533fd'} |
Sep 16 00:34:42 ip-10-0-11-96 cloud-init[1125]: | distributed | 2022.6.0    | 2022.6.0  | {'2022.6.0', '2022.9.0+13.g1fd07f03'} |
Sep 16 00:34:42 ip-10-0-11-96 cloud-init[1125]: +-------------+-------------+-----------+---------------------------------------+
```

**Comment by ntabris** [comment]
possibly same problem as https://github.com/coiled/platform/issues/84

**Comment by ian-r-rose** [comment]
Thanks @ntabris, is this deployed yet? If not, I'd propose skipping this test until then.

**Comment by shughes-uk** [comment]
Should be deployed now
