### ISSUE TITLE
add timestamps to logger in benchmarks/CI

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#356]

**Comment by jrbourbeau** [comment]
Thanks @ntabris. Do you have a CI build where logs are being emitted? IIRC this only happens when something goes wrong with a `coiled` cluster

**Comment by ntabris** [comment]
> Do you have a CI build where logs are being emitted? IIRC this only happens when something goes wrong with a coiled cluster

I don't have a specific case in mind. I think you're probably right that (eg) Coiled client logs only appear when there's a failure. Timestamps on that would be nice.

Maybe we could also use https://pypi.org/project/pytest-timestamper/ and timestamp each test?

Timestamps are a big help when trying to correlate with anything on the infra side.

**Comment by jrbourbeau** [comment]
Gotcha, thanks @ntabris. Do you think other users would benefit from timestamps on Coiled client logs? I'm wondering if it would be better to change the logger formatting upstream directly in `coiled`

**Comment by ntabris** [comment]
>  Do you think other users would benefit from timestamps on Coiled client logs? I'm wondering if it would be better to change the logger formatting upstream directly in coiled

(Sorry, meant to reply sooner but forgot.)

Our approach is to let the user configure the logger, since my understanding is that it's tricky to change the defaults but also not interfere with various ways that the user might try to change the logger config. I believe @dchudz is more familiar with this than me.

**Comment by dchudz** [comment]
Like Nat said... my understanding is it's best practice for libraries (like Coiled) *not* to configure the logger.

**Comment by ntabris** [comment]
@jrbourbeau could someone do this please? I'm hoping this is easy but maybe I'm wrong.

As an example of where I'd really really like to have timestamps, here's a timeout waiting for workers and I don't know when this happened:

https://github.com/coiled/coiled-runtime/actions/runs/3395268406/jobs/5644924689#step:5:266

(I'm trying to understand https://github.com/coiled/coiled-runtime/issues/468)

**Comment by dchudz** [comment]
Thanks James!
