### ISSUE TITLE
Deadlock Reproducer

### ISSUE THREAD

**Issue by hayesgb** [coiled/coiled-runtime#37]
https://github.com/dask/distributed/issues/5951

@sjperkins -- Not sure if you saw this, and I believe it was incorporated as a unit test, but raising it here if it makes sense to include as part of the stability work you're doing.

**Comment by sjperkins** [comment]
> @sjperkins -- Not sure if you saw this, and I believe it was incorporated as a unit test, but raising it here if it makes sense to include as part of the stability work you're doing.

I've added this as a case  to https://github.com/coiled/oss-engineering/issues/94

**Comment by ncclementi** [comment]
@hendrikmakait and @gjoseph92 is this something we can close or should keep this around?
