### ISSUE TITLE
Benchmarks consistently failing

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#386]
We're seeing benchmarks consistently fail on `main`. Testing things out in https://github.com/coiled/coiled-runtime/pull/378

cc @crusaderky @ian-r-rose @ncclementi

**Comment by crusaderky** [comment]
@ntabris mentioned yesterday he believed it was an infra problem.
Everything looks green again today

**Comment by jrbourbeau** [comment]
Great, thanks for following-up @crusaderky
