### ISSUE TITLE
Ability to zoom in on benchmarking plots

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#416]
I ran across this plot

<img width="856" alt="Screen Shot 2022-10-03 at 12 30 04 PM" src="https://user-images.githubusercontent.com/11656932/193641637-10e9b3b2-cbc1-480e-be2d-a6585a739e90.png">

and wanted to zoom in on the y-axis to manually filter out the large outlier point. It'd be great if we could select a specific region of these plots to zoom in

**Comment by ncclementi** [comment]
For some reason, this was not closed when linked to the PR that was merged. So closing, as this https://github.com/coiled/coiled-runtime/pull/421 was merged.
