### ISSUE TITLE
Raise issue when CI on `main` fails

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#43]
If CI fails for some reason on a push to `main`, it'd be good for us to have that visible (today there's just a red X that most folks won't notice). Dask's `upstream` CI build opens an issue when there's a failure on `main` and leaves a comment linking to the corresponding CI build. We can reuse that GHA workflow here.

**Comment by ncclementi** [comment]
Leaving a link to the `upstream.yml` from dask that will be of inspiration of this https://github.com/dask/dask/blob/main/.github/workflows/upstream.yml
