### ISSUE TITLE
compare costs w/ non-burstable instance types

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#444]
Most of the tests currently use `t3`. For these, you pay extra if you have longer durations of high-CPU load.

This is what we're paying extra, in addition to the base `t3` instance cost:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/46289310/195408081-458caf80-50fd-4cc8-8224-1c604a202c16.png">

And here are the base `t3` instance costs for same period:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/46289310/195408263-e96c4763-1846-48ff-bc86-dfa00a088b93.png">

I suspect that switching off `t3` to something w/ higher base cost but no charge for high CPU util would save money. We (probably me) should check this.

**Comment by ntabris** [comment]
This is also maybe a thing to think about in how we (platform) suggest instance types for people, it's definitely possible `t3` would be more expensive for various workloads than `m6i` (which also potentially gets better network bandwidth).

**Comment by shughes-uk** [comment]
I'd take into consideration availability and free tier quota ect for whatever we pick as the default.

**Comment by ntabris** [comment]
At least for coiled-runtime tests, using `m6i` instead of `t3` has reduced cost and also (somewhat to my surprise) makes a non-trivial difference in perf.

Here's chart of t3 "burst" usage/cost:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/46289310/200873840-3fe9aa2b-8fd7-4436-9e16-21a480b20934.png">

We'll need to think more about what this means for instance types on the Coiled platform more generally.
