### ISSUE TITLE
Automatically capture (and upload) cluster dump on integration test failure

### ISSUE THREAD

**Issue by gjoseph92** [coiled/coiled-runtime#45]
Follow-up to https://github.com/coiled/coiled-runtime/pull/41

I'm not actually sure how useful a cluster dump would be in many cases. But my first question in seeing https://github.com/dask/distributed/issues/6125 was to think, "can we get a cluster dump for this"? The worker event logs might be helpful.

An S3 bucket that the GHA runners have access to might be a logical place to upload (since `dump_cluster_state` already supports it).

**Comment by mrocklin** [comment]
Yeah, I agree that that would be handy.  Do you have thoughts on the right way to do this?  (I don't have any experience here)

**Comment by jrbourbeau** [comment]
Instead of hooking into `pytest_exception_interact` I was thinking about a `try`/`except` around the place that we yield `Client`s. Something like (pseudo-code below):

```python
with Client(cluster) as client:
    try:
        yield client
    except Exception:
        client.dump_cluster_state(...)
```

thoughts? 

> I'm thinking of implementing this for the stability tests

I was thinking this would be most relevant for stability tests too. That said, if it's easier from an implementation perspective we might try producing cluster dumps for any test failure and then in the future restrict to just stability test (perhaps gated by an environment variable?) if needed

**Comment by ncclementi** [comment]
My concern about dumping on every Exception is that we might end up with more cluster dumps than the ones we are really interested in. 

@gjoseph92 are we looking for any exceptions here to be intercepted, or do we have a way to narrow this down a bit?

I like the idea of an os env variable and setting it to True for the cases of interest. The code snippet above would be to modify the current small_client fixture in here https://github.com/coiled/coiled-runtime/blob/6dab08feeba52291560fa248e1d9881d4f669c1f/conftest.py#L81-L87

```python
@pytest.fixture
def small_client(small_cluster):
    with Client(small_cluster) as client:
        small_cluster.scale(10)
        client.wait_for_workers(10)
        client.restart()
        try:
             yield client
        except Exception:
               cluster_dump = strtobool(os.environ.get("CLUSTER_DUMP, "false"))
               if cluster_dump:
                    client.dump_cluster_state(...)
               else:
                   pass # I wonder if passing here is the right thing
```

Then on the stability jobs, we flip the os env variable to "true". I'll open a draft PR on this, and we can build based on that.
