### ISSUE TITLE
`package_sync` includes `coiled-runtime` even if it has not been installed

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/coiled-runtime#456]
When starting a Coiled cluster within the project root, `package_sync` somehow picks up `coiled-runtime==0.1.0` even if it has not been installed. This creates issues when trying to run integration tests with development versions of `dask` and `distributed`.

**Reproducer**

1. Create a new virtual environment and navigate to `coiled-runtime` root
```bash
conda create -n sandbox coiled
conda activate sandbox
cd <PATH_TO_COILED_RUNTIME_ROOT>
```
2. Within the project root, execute the following python code (e.g. in `ipython`)
```python3
from coiled.v2 import Cluster
cluster = Cluster(name="test_sync", package_sync=True)
...
```
3. Navigate to _Cluster Details_ on https://cloud.coiled.io and check software (e.g., https://cloud.coiled.io/dask-engineering/clusters/96730/details)

**Comment by hendrikmakait** [comment]
After some more investigation, this issue appears as long as the `coiled-runtime.egg-info` folder is around. When removing it, `package_sync` does not pick up `coiled-runtime` anymore.

**Comment by hendrikmakait** [comment]
cc @shughes-uk

**Comment by shughes-uk** [comment]
I need to confirm this but technically the coiled runtime package is part of your environment when you launch like this. The problem comes from coiled runtime being a metapackage with specific pins. In general package sync requires your environment to be solvable with pip/conda to function correctly in its current state.

 I'll add the coiled runtime to the ignore list to solve this specific issue though.

**Comment by shughes-uk** [comment]
Coiled runtime is now ignored in prod @hendrikmakait if you want to confirm this now works

**Comment by hendrikmakait** [comment]
@shughes-uk, thanks for taking care of this, things work as expected now.

> technically the coiled runtime package is part of your environment when you launch like this.

I had not thought about it this way, but I guess you're right. That's yet another reason to split the tests from the metapackage building.
