### ISSUE TITLE
Fix Windows CI issue when testing latest `coiled-runtime`

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#49]
In https://github.com/coiled/coiled-runtime/pull/33 we explicitly excluded running Windows builds against the latest `coiled-runtime` in CI

https://github.com/coiled/coiled-runtime/blob/95ba3528faefc6302274ecc3f4155e836c3ba54b/.github/workflows/conda.yml#L29-L32

due to the issue described in https://github.com/coiled/coiled-runtime/pull/33#discussion_r849753447. Opening this issue so we remember to go back and fix that and re-introduce Windows builds for the latest `coiled-runtime`

**Comment by ncclementi** [comment]
Hi @crusaderky may I invoke your CI sorcery skills over here? I know you have done a lot of work with CI and windows, have you ever seen this error? Trying to find a place to start debugging this issue.
