### ISSUE TITLE
Invalid Coiled token

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#51]
It looks like the token we've been using in CI is no longer valid

> Run # If testing the latest `coiled-runtime`, we need to build a Coiled software environment
Creating Coiled software environment for dask-engineering/coiled-runtime-pull_request-47-d679a56bbeb127140cd56d477d6a7bd9e8032ad2-ubuntu-latest-py38
Invalid Coiled token encountered. You can create new tokens and manage your 
existing ones at https://cloud.coiled.io/profile.

> Please login to https://cloud.coiled.io/profile to get your token
/usr/share/miniconda3/envs/test/lib/python3.8/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Token:
Warning: Password input may be echoed.
 Aborted!

See [this CI build](https://github.com/coiled/coiled-runtime/runs/6028345346?check_suite_focus=true) for an example.

cc @ncclementi any thoughts on why this might be?

**Comment by ncclementi** [comment]
No idea, what could have happened? The token is not supposed to expire, maybe someone from platform can advice us here? 
![Screen Shot 2022-04-14 at 1 51 10 PM](https://user-images.githubusercontent.com/7526622/163448975-535b0766-2b7f-459b-8beb-205b9c9e4946.png)

@jrbourbeau could it be you are opening a PR from your fork?
![Screen Shot 2022-04-14 at 2 01 44 PM](https://user-images.githubusercontent.com/7526622/163450125-71d4ba70-e472-4bc8-9d14-3005f4f026d2.png)

**Comment by jrbourbeau** [comment]
Whoops, that's exactly what the problem is. Thanks for catching that @ncclementi. Apologies for the noise all
