### ISSUE TITLE
Dask Dashboard not loading with strange error message

### ISSUE THREAD

**Issue by rrpelgrim** [coiled/coiled-runtime#525]
I'm trying to reproduce the Dask benchmarking done here: https://github.com/EthanRosenthal/medium-data-bakeoff

To test, I've created a new environment and run `conda install coiled-runtime python-duckdb kaggle loguru tqdm`. 
When I launch a cluster and try to open up the dashboard I get the following error message: 

```
Dask needs bokeh >= 2.1.1 for the dashboard.
Install with conda: conda install bokeh>=1.0
Install with pip: pip install bokeh>=2.1.1
```

Besides the fact that the `conda` instructions are incorrect, this is an odd message because `bokeh==3.0.1` is installed in the environment.

Running `conda update bokeh` doesn't solve this because conda says all packages are updated.

**Comment by rrpelgrim** [comment]
Just tried again with an env created using `conda install coiled dask python-duckdb kaggle loguru tqdm`. In this env, the Dask dashboard *is* working. This env solves with `bokeh==2.4.3`.

**Comment by ntabris** [comment]
Sounds like duplicate of https://github.com/coiled/coiled-runtime/issues/520 (the problem there wasn't `pip` specific as far as I can tell)

**Comment by rrpelgrim** [comment]
Thanks @ntabris - looks a duplicate indeed. closing.
