### ISSUE TITLE
Patch release 0.1.1 pining bokeh

### ISSUE THREAD

**Issue by ncclementi** [coiled/coiled-runtime#530]
It's not clear that we can do a release 0.2.0 bumping up all the packages see 
- https://github.com/coiled/coiled-runtime/issues/526

However, due to the unpin version of bokeh in distributed the current runtime breaks the dashboard see https://github.com/coiled/coiled-runtime/issues/520. 

Action items.
- [x] Reverting the packages version of the runtime to the versions in 0.1.0 and add bokeh=2.4.3
- [x] Do a release

**Comment by dchudz** [comment]
+1

**Comment by dchudz** [comment]
>  Reverting the packages version of the runtime to the versions in 0.1.0 and add bokeh=2.4.3

Do you really have to revert?

I'd expect the easiest we to do this kind of patch release is:

1. branch off the `0.1.0` tag
2. update the bokeh pin and tag as `0.1.1`
3. release that

**Comment by ncclementi** [comment]
@dchudz there is already a plan of action, we don't want to do a release without reverting the updates because there are some broken things on newer versions plus some regressions we don't yet understand. If you want to learn more about that, read https://github.com/coiled/coiled-runtime/issues/526 but more specifically https://github.com/coiled/coiled-runtime/issues/500. 

The release was a bit delayed due to other issues but now we should be good to go. I'll have the release done in the next hour, have a few things to take care of first.

**Comment by ncclementi** [comment]
Closing as the release has been done in both pypi and conda-forge

**Comment by jrbourbeau** [comment]
Woo -- thanks @ncclementi!
