### ISSUE TITLE
stop testing old versions

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#547]
It looks like we're currently testing 0.0.4 and 0.1.0:

https://github.com/coiled/coiled-runtime/blob/bfa92b7f19eb33b686d1947b49cd84ab8a5c4f64/.github/workflows/tests.yml#L35

Can we just test 0.1.1 instead? (What's the LTS period for 0.0.4? and does LTS still apply to 0.1.0, or can we say LTS means that patch replaces 0.1.0?)

**Comment by jrbourbeau** [comment]
Thanks @ntabris -- +1 for dropping 0.0.4. Technically, we support the last two releases of the runtime (i.e. 0.1.0 and 0.1.1 as of today). So, for now, I'll suggest we drop 0.0.4 and add 0.1.1.

@ncclementi is this something you have bandwidth for?

**Comment by ntabris** [comment]
Your call and I don't care a lot but "last two" seems odd in this case given that `0.1.1` is patch to fix problem with `0.1.0`, right?

**Comment by jrbourbeau** [comment]
Yeah, I agree "last two" combined with patch releases seems a bit off. At the same time, I'm inclined to not think much about this for the time being (unless there's an issue with the current rule) 

cc @hayesgb, who is out the rest of the week on PTO, who might have thoughts on this topic

**Comment by ntabris** [comment]
Yep, not a big deal either way as far as I'm concerned (and maybe moot soonishly if we release 0.2.0...)

(It makes me sad that the word "moot" means "non-actionable" but alas.)

**Comment by ncclementi** [comment]
+1 for dropping 0.0.4 

I did not add 0.1.1, because it is 0.1.0 +bokeh and we have better test history for 0.1.0. I did not want to create another entry on the dashboard, and track 2 things that test-wise are the exact same. So I would say keep 0.1.0 around.
