### ISSUE TITLE
Add xarray and zarr to coiled-runtime

### ISSUE THREAD

**Issue by mrocklin** [coiled/coiled-runtime#56]
The user / bug ratio on Xarray and Zarr are pretty high.  I suspect that we could add them without much fuss.  I'm mildly in favor.

Thoughts?

**Comment by hayesgb** [comment]
I can't comment on the occurrence of bug reports.  If including them means delaying, I'd prefer to add in the next release.

FWIW -- xarray is in the coiled default environment, but zarr is not.

**Comment by mrocklin** [comment]
What delay would this cause?  I'm thinking of just adding xarray and zarr to the metapackage.

**Comment by mrocklin** [comment]
For xarray in a cloud setting you would also want zarr

**Comment by hayesgb** [comment]
> What delay would this cause?

Probably none.  It's a qualifier.  We didn't expect to encounter an issue with Python3.7 support either, which it sounds like was fixed with `coiled==0.0.74`

> For xarray in a cloud setting you would also want zarr

Agreed.

**Comment by hayesgb** [comment]
cc @jrbourbeau -- FYI

**Comment by jrbourbeau** [comment]
Sure, I don't have an objection to adding `xarray` and `zarr`. Matt's correct about their high user / bug ratio. `zarr` is also widely used in Dask Array workloads, so should probably be included for that reason too. Will push something up for this

**Comment by mrocklin** [comment]
Thanks @jrbourbeau .  I appreciate both the "can do" attitude, and the short duration from idea to shipping.
