### ISSUE TITLE
Test P2P Shuffle in integration tests

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/coiled-runtime#569]
Parametrize tests to use the `tasks` and `p2p` shuffle

* [x] `test_shuffle`
* [x] `test_join` 
    * [ ] BONUS: Enable larger data sizes for `p2p`
* [x] `test_h2o_benchmarks`

Only run for `2022.11.0` and larger (which includes https://github.com/dask/distributed/commit/9c6904df38495e90af776aecb24f4a495ebda028)

**Comment by ncclementi** [comment]
For the BONUS, we can check that out. We do have a 50GB and  500GB dataset version of the h2o-benchmark groupby data on S3 where id1, id2, id3 are as pyarrow strings here 
50GB: s3://coiled-datasets/h2o-benchmark/pyarrow_strings/N_1e9_K_1e2/
500GB: s3://coiled-datasets/h2o-benchmark/pyarrow_strings/N_1e10_K_1e2/
