### ISSUE TITLE
Fail to build and push to docker for runtime 0.2.0

### ISSUE THREAD

**Issue by ncclementi** [coiled/coiled-runtime#579]
As part of the relaase of the runtime 0.2.0, we needed to create the docker images to create the coiled software environments. 

This process is done via the `` workflow. However, there were/are some failures that are preventing this. 
https://github.com/coiled/coiled-runtime/actions/runs/3603086081

The main error is in `runtime=0.2.0` and `py38`: Where strangely complains about py37 even though it's py38. 
```
 #10 61.38 Encountered problems while solving:
#10 61.38   - nothing provides openssl >=1.0.2p,<1.0.3a needed by python-3.7.1-hd75c258_1001
#10 61.38 
#10 61.38 The environment can't be solved, aborting the operation
#10 61.38 error    libmamba Could not solve for environment specs
#10 61.41 critical libmamba UnsatisfiableError
```
Without this images we can't build the coiled-software environments for `runtime=0.2.0`

cc: @dchudz @ntabris @jrbourbeau

**Comment by jrbourbeau** [comment]
Thanks for reporting @ncclementi -- I agree seeing things about Python 3.7 in this build is weird. 

@dchudz @ntabris I think this means we won't have published docker images / Coiled software environments for `coiled-runtime=0.2.0` for Python 3.8. What impact does this have on Coiled's default behavior? Do things break, or just pull in a non-latest software environment? I'm trying to get a sense for priority on this issue

**Comment by dchudz** [comment]
> Do things break, or just pull in a non-latest software environment?

`just pull in a non-latest software environment` I think.

In more detail, Coiled will:

1. attempt to match a runtime version it finds locally
2. if no runtime version locally, find that latest software env that matches `env.endswith(py_version) and "coiled/coiled-runtime" in env`.

Relevant code:

<details>
```
    async def _determine_senv(self):
        # Attempt to match Coiled software environment to local versions of Python and coiled-runtime
        # FIXME get local coiled-runtime version when it was installed with pip
        warn_for_unspecified_senv = False
        if self.software_environment is None and not self.package_sync:

            py_version = f"py{''.join(map(str, sys.version_info[:2]))}"
            warn_for_unspecified_senv = True
            try:
                senvs = await self.cloud.list_software_environments(account="coiled")  # type: ignore
                runtime_versions = [
                    env
                    for env in senvs
                    if env.endswith(py_version) and "coiled/coiled-runtime" in env
                ]
                self.software_environment = max(runtime_versions, key=name_to_version)  # type: ignore
            except ValueError:
                self.software_environment = f"coiled/default-{py_version}"
            conda_prefix = environ.get("CONDA_PREFIX")
            if conda_prefix:
                conda_meta = Path(conda_prefix) / "conda-meta"
                if conda_meta.exists():
                    coiled_runtime = next(conda_meta.glob("coiled-runtime*.json"), None)
                    if coiled_runtime:
                        match = re.match(
                            r"coiled-runtime-(\d+\.\d+.\d+)", coiled_runtime.name
                        )
                        if match:
                            runtime_version = match[1].replace(".", "-")
                            self.software_environment = (
                                f"coiled/coiled-runtime-{runtime_version}-{py_version}"
                            )
                            warn_for_unspecified_senv = False
```
</details>

**Comment by jrbourbeau** [comment]
Okay, good to know. Given that, I don't see this issue as an emergency, but something that would still be good to address. If I were to look into this more, the next thing I would do is see if I can reproduce locally inside the docker image build. 

cc @hayesgb for visibility

**Comment by ncclementi** [comment]
I'm also seeing that the jobs for some of the 0.1.1 runtime got canceled see https://github.com/coiled/coiled-runtime/actions/runs/3603086081

**Comment by ncclementi** [comment]
Seeing same problem when trying to build the images for runtime 0.2.1 seeing the same problem. I tried on a separate branch upgrade mircomamba to their latest release, but I continue seeing this issue. 

Python 3.10 build, 3.8 failed, and 3.9 hanged for a long time so I stopped the job. 
https://github.com/coiled/coiled-runtime/actions/runs/3705608964/jobs/6279735279

**Comment by ntabris** [comment]
Same effect, but in 0.2.0 I was seeing a solve error, not seeing that here.

This is impacting a user on Coiled side who's trying to use runtime 0.2.1 py39.

It appears there's already a retry of the pipeline running, that could resolve, if not I think this should get some attention.

**Comment by ncclementi** [comment]
Ok
> This is impacting a user on Coiled side who's trying to use runtime 0.2.1 py39.
Is this because they are trying to use the soft env instead of package sync? 


>It appears there's already a retry of the pipeline running, that could resolve, if not I think this should get some attention.

I'm experimenting with some things, I want to see if python 3.9 finishes at least. 
I will try separately only build py-38 for amd and avoid arm. 

If things do not work, I agree this will need some attention but I'm not sure who will be able to debug what's happening with docker.

**Comment by ntabris** [comment]
> I will try separately only build py-38 for amd and avoid arm.

I think that's best way to address.

For py38, it seems the solve is just consistently failing for ARM. Also, @shughes-uk told me yesterday that the mamba error messages about why solve failed are often just wrong, so it's a pain to debug.

We could either (1) debug this and get solve that works for ARM with py3.8 or (2) disable the ARM build for py3.8.

My inclination is (2). We don't have many people trying ARM yet, if need be we can tell anyone trying ARM w/ coiled-runtime to use py39 or py310.

If I'm reading https://numpy.org/neps/nep-0029-deprecation_policy.html correctly, maybe we'll drop py38 after Jan 31, 2023, anyway.

**Comment by ntabris** [comment]
Yay, we now have multiarch 3.9 and 3.10 images on docker hub:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/46289310/207917540-4e402e01-4bc3-4b75-828b-ad4f522eed60.png">

Thanks @ncclementi for kicking off that re-run to make these.

**Comment by ncclementi** [comment]
@ntabris I was able to build and push just for py38 in amd (we should have that one too). I'm going to play with the GHA to make sure we skip arm for py38 for now.
