### ISSUE TITLE
Patch release 0.2.1

### ISSUE THREAD

**Issue by hayesgb** [coiled/coiled-runtime#582]
`pyarrow>=10` has been on pypi since October 27th, but is still not available on conda-forge.  This blocks us from adding `pyarrow>=10` to the `coiled-runtime` metapackage.  

Need to watch open PRs here:  https://github.com/conda-forge/arrow-cpp-feedstock/pulls , and make a patch release when its available.

**Comment by ncclementi** [comment]
- pypi https://pypi.org/project/coiled-runtime/
- Conda forge: https://anaconda.org/conda-forge/coiled-runtime
