### ISSUE TITLE
"latest" tests still using 2022.11.1

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#584]
Tests have run since 2022.12.0 was released but "latest" doesn't appear to be using it:

https://benchmarks.coiled.io/coiled-latest-py3.9.html

**Comment by ncclementi** [comment]
Nat, for reference latest is what is on the recipe in main on the runtime repo, what you are looking for is upstream. See 
https://benchmarks.coiled.io/coiled-upstream-py3.9.html

![Screen Shot 2022-12-05 at 10 31 06 AM](https://user-images.githubusercontent.com/7526622/205676629-c115c06e-848b-479c-bfac-439819f160eb.png)

**Comment by ntabris** [comment]
Yes, I know that upstream currently matches latest. That won't be the case for long. "latest" should be latest release, right?

**Comment by ncclementi** [comment]
>Yes, I know that upstream currently matches latest. That won't be the case for long. "latest" should be latest release, right?

Upstream will match main of dask and distributed. 

Latest, is what is the latest on the main coiled-runtime repository recipe. It's usually the same than the latest release of the runtime, until we start testing potential new packages for the future release.

**Comment by ntabris** [comment]
> It's usually the same than the latest release of the runtime, until we start testing potential new packages for the future release.

Oh, weird, I thought it was supposed to be latest release of dask/distributed, but I think you're saying that's not the case. So "latest" is supposed to be testing the same versions as 0.2.0? Why do we have both?

**Comment by ncclementi** [comment]
> Oh, weird, I thought it was supposed to be latest release of dask/distributed, but I think you're saying that's not the case.
Correct this is  not the case. When it was designed it was supposed to be the testing the packages that are here https://github.com/coiled/coiled-runtime/blob/main/recipe/meta.yaml

>  So "latest" is supposed to be testing the same versions as 0.2.0? Why do we have both?
At the moment is doing this, but it was meant to be what tests the potential new candidates for the following release. 

But I do agree that at the moment is testing the same, that the 0.2.0 release and this is not useful. It might be worth having a discussion to define what is the most useful thing to test for this case.

**Comment by ntabris** [comment]
@ncclementi thanks, I think the explanation is finally starting to sink in. Does "latest" effectively mean "thing we're testing as a coiled-runtime RC"?

**Comment by ncclementi** [comment]
> @ncclementi thanks, I think the explanation is finally starting to sink in. Does "latest" effectively mean "thing we're testing as a coiled-runtime RC"?

Technically yes, tbh we haven't done that much in practice. But it was the intention.

**Comment by ncclementi** [comment]
Closing this, as the initial question was clarified. We should open a separate issue if what we want is discuss what is being tested in latest and how should it change.
