### ISSUE TITLE
Split Coiled Runtime into Benchmarks and Stability/Integration

### ISSUE THREAD

**Issue by hayesgb** [coiled/coiled-runtime#594]
Currently, the `coiled-runtime` repo is serving multiple functions.

- Testing Dask at (some) scale
- Evaluating dask's performance in conjunction with other libraries
- Testing scalability (in a limited sense)
- <Some> benchmarking
- Evaluating infrastructure performance
- ...

Given our current state, I'll propose we split out benchmark tests with the intent of scaling these to larger datasets.  This will (at least partially) address #483, while also hitting the larger goal of better evaluating performance at scale.

cc: @fjetter , @jrbourbeau , @crusaderky , @gjoseph92

**Comment by crusaderky** [comment]
A/B tests, which are also used for scalability, already have the option to cherry-pick which of the three subfolders you want to run on, with only benchmarks being enabled by default:
https://github.com/coiled/coiled-runtime/blob/0aa0047dd3f091ccf325d57a244baebc77e5c2f5/AB_environments/config.yaml#L12-L16

Regular (nightly and PR) tests have different granularity (stability runs on everything; benchmarks and runtime run only on Linux python 3.9).

Not sure what else is there to do?
