### ISSUE TITLE
understand scheduler/interzone network traffic

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#598]
# The question

Is it okay to turn on `use_best_zone`, or is this likely to add significant cost because of non-trivial amount of traffic between scheduler and workers?

I see non-trivial interzone traffic on some coiled-runtime tests... is this typical, or is this because we're doing unusual things?

@hayesgb I'd appreciate help on this, we were hoping to enable `use_best_zone` as the default but this is potentially a blocker.

# What I'm seeing

We're hoping that `use_best_zone` is something we can turn on by default. This option makes it easier to get large numbers of spot instances, but it also means that scheduler may be in a different zone (in same region) as the workers, so traffic between scheduler and workers is "interzone".

It's been on since Nov 16 for coiled-runtime CI. It doesn't appear to have (noticeable) impact on performance.

But it does appear to sometimes have non-trivial impact on cost. Traffic within a zone is free, traffic between zones is not.

Here are per day network costs in November:

![image](https://user-images.githubusercontent.com/46289310/206201185-1f023061-738a-4871-bcc0-ecf68a643869.png)

Here's are costs for an individual CI (GITHUB_RUN_ID 3534162161) run on November 23 that had a lot (~524GB) of interzone traffic:

![image](https://user-images.githubusercontent.com/46289310/206201292-72def55c-b34d-4f37-bda2-08994e432c77.png)

Anything interzone is going to be between scheduler and workers since those are the only things in different zones, so to understand this I've been looking at hardware metrics for scheduler traffic.

For the relevant period on November 23, here's chart of **sent** bytes over time for every scheduler:

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/46289310/206201869-16f8a933-8102-4101-bed2-95162bb28fe3.png">

[grafana dashboard of scheduler network](https://grafana.dev-sandbox.coiledhq.com/d/Szis4QKVz/scheduler-network?orgId=1&from=1669222800000&to=1669231800000)

It appears that every `test_array` scheduler send 500–700MB, `test_join` schedulers send 410–420MB, and `h2o` send 160–180MB.

Looking at a specific cluster, it appears that this traffic is spread over the life of the cluster:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/46289310/206203092-1e353330-d779-44c4-91c0-0cdf52aba743.png">

[grafana for test_array-26e9989e](https://grafana.dev-sandbox.coiledhq.com/d/eU1bT-nVz/cluster-metrics-prometheus?orgId=1&from=1669227192907&to=1669229181899&var-datasource=default&var-env=All&var-account=dask-engineering&var-cluster=test_array-26e9989e&var-cluster_id=115796)

For example, in the same ~1min period when the workers did this work:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/46289310/206203738-157de086-6986-4234-a654-6e4a47179fcd.png">

The scheduler was doing this:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/46289310/206203826-609506f6-9c8d-41a5-8d87-07198df7b9e1.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/46289310/206204921-e6772885-425c-41f6-a05a-cb67e8a7d1b9.png">

**Comment by fjetter** [comment]
Do we pay for egress traffic as well, i.e. stuff like Worker->Client? The result fetching is going by default over the scheduler but it is also possible to set it up such that clients connect directly to the workers to fetch results (Are workers even reachable from the client? I have to admit that I have no idea how our network topology looks like).
The same is true for use cases that use `Client.scatter`. This literally sends payload data to the scheduler which is then redistributed to the workers from there. Can also be direct but isn't by default. We're not using this in our tests afaik.

> or is this likely to add significant cost because of non-trivial amount of traffic between scheduler and workers?

How much cost is "significant"? The test_array example transfers ~600MB. How much is the network cost in relation to the total cost of this run?

> We're hoping that use_best_zone is something we can turn on by default. This option makes it easier to get large numbers of spot instances, but it also means that scheduler may be in a different zone (in same region) as the workers, so traffic between scheduler and workers is "interzone".

Are all workers always in the same AZ? Traffic between workers is typically significant.

**Comment by ntabris** [comment]
> Do we pay for egress traffic as well, i.e. stuff like Worker->Client?

Yes we do. Ingress is free, egress is billed.

> Are workers even reachable from the client?

As we configure things, workers can only receive **inbound** connections from inside the cluster. The security group works as a stateful firewall, so workers can open connections to anywhere they like, just can't receive new connections from outside.

(@crusaderky was bringing up the possibility of direct connections to workers rather than going through scheduler for everything. In theory we could make that work, it doesn't feel worth it, and my sense is that disabling TLS for intracluster comms would have significant impact on perf and is something that requires having firewall around the cluster like we have today.)

> How much cost is "significant"? The test_array example transfers ~600MB. How much is the network cost in relation to the total cost of this run?

Obviously this is going to depend but I was seeing 5–10%. Which might be fine for some people, and it's much lower for some clusters, but it's high enough to give us pause on turning this on by default since there are tradeoffs.

> Are all workers always in the same AZ? Traffic between workers is typically significant.

Yes, very much aware of this and the importance of keeping workers in same AZ.

**Comment by crusaderky** [comment]
https://github.com/dask/distributed/issues/7386 for a potential low-hanging fruit

**Comment by fjetter** [comment]
@crusaderky Re https://github.com/dask/distributed/issues/7386#issuecomment-1346519857

I'm not super excited about 10%. In the context of this issue, this would safe us 0.5-1% cost in some cases (leaning on Nats estimate above). Many workloads would be entirely oblivious to this. Assuming, of course, we'd even enable this feature.

@ntabris do you think it's worth on our end to tune this to reduce transmitted size by ~10%?

**Comment by ntabris** [comment]
Here's chart showing costs for compute vs interzone traffic:

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/46289310/207095730-0fb2218f-7dba-45af-803a-ab9fad405e66.png">

[cost explorer](https://us-east-1.console.aws.amazon.com/cost-management/home?region=us-west-2#/custom?groupBy=Service&hasBlended=false&hasAmortized=false&excludeDiscounts=true&excludeTaggedResources=false&excludeCategorizedResources=false&excludeForecast=false&timeRangeOption=Custom&granularity=Daily&reportName=&reportType=CostUsage&isTemplate=true&filter=%5B%7B%22dimension%22:%22UsageType%22,%22values%22:%5B%7B%22value%22:%22USE2-BoxUsage:c5.12xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:c5.2xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:c5.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:c5.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:c5n.18xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:c7g.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:g4dn.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:i3.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:i3.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5.16xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5.4xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5.8xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5a.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5a.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5ad.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5ad.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5d.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5n.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m5zn.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6a.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6g.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6g.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6i.2xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6i.4xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6i.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6i.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6id.4xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6id.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6id.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:m6in.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:r5.8xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:r5a.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:r5b.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:r6i.2xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:r6i.32xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:r6i.8xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t2.medium%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t3.2xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t3.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t3.medium%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t3.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t3a.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t3a.medium%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t3a.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-BoxUsage:t4g.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-DataTransfer-Regional-Bytes%22,%22unit%22:%22GB%22%7D,%7B%22value%22:%22USE2-SpotUsage:c5a.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m5.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m5.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m5a.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m5ad.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m5dn.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m5n.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m5zn.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m6a.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m6a.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m6i.2xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m6i.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m6i.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m6id.4xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m6id.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:m6id.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:t3.large%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:t3.medium%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:t3.xlarge%22,%22unit%22:%22Hrs%22%7D,%7B%22value%22:%22USE2-SpotUsage:t3a.large%22,%22unit%22:%22Hrs%22%7D%5D,%22include%22:true,%22children%22:null%7D%5D&chartStyle=Stack&forecastTimeRangeOption=None&usageAs=usageQuantity&startDate=2022-11-28&endDate=2022-12-11)

It appears to be somewhat consistently ~5%.

On a call w/ @crusaderky and @fjetter I've already said this but sharing for others: at present the thing I care about more is the fact that there's potentially larger transfer of data from workers to client that goes through scheduler (return multiple GBs of result to client).

My plan is to **not** have `use_best_zone` on by default (at least in the short term), though I think it does make sense to suggest to customers who run into issues w/ instance availability. We (most likely me) will look into ways the achieve the desired effect while ensuring workers and scheduler are in same zone.

**Comment by crusaderky** [comment]
> @crusaderky Re [dask/distributed#7386 (comment)](https://github.com/dask/distributed/issues/7386#issuecomment-1346519857)
> 
> I'm not super excited about 10%. In the context of this issue, this would safe us 0.5-1% cost in some cases (leaning on Nats estimate above). Many workloads would be entirely oblivious to this. Assuming, of course, we'd even enable this feature.

It would actually be 35% of 5%, so a ~2% total saving for Coiled clients.
As discussed at standup, it would be however dwarfed by scatter/gather activity unless the users are very careful to always read/write to s3 or other dbs.

**Comment by mrocklin** [comment]
> My plan is to not have use_best_zone on by default (at least in the short term), though I think it does make sense to suggest to customers who run into issues w/ instance availability. We (most likely me) will look into ways the achieve the desired effect while ensuring workers and scheduler are in same zone.

This seems like the kind of thing where even though we can't make an automatic determination for the customer, we might be able to give them some information to help them make better choices.

This also feels like the kind of thing that could be part of a cost management blog

**Comment by ntabris** [comment]
> This seems like the kind of thing where even though we can't make an automatic determination for the customer, we might be able to give them some information to help them make better choices.

> This also feels like the kind of thing that could be part of a cost management blog

Yep, that's what I'm thinking.

**Comment by ntabris** [comment]
Okay, so I did some more digging and decided and found that the impact of delaying scheduler until worker zone has been determined isn't significant (at least for AWS, where we have the most data), and that's now what we do.

Previously we were seeing ~24GB of interzone data (between scheduler and workers) with cost of ~$0.24 per CI run. Change was deployed last night and I'd now expect to see no interzone traffic (can't confirm yet because cost explorer doesn't yet have most recent data).
