### ISSUE TITLE
coiled.errors.ServerError: detail=User inactive or deleted.

### ISSUE THREAD

**Issue by crusaderky** [coiled/coiled-runtime#630]
coiled-runtime CI has started mass-failing with this error:

https://github.com/coiled/coiled-runtime/actions/runs/3749408817/jobs/6367944744

FAILED tests/benchmarks/test_work_stealing.py::test_work_stealing_on_scaling_up - coiled.errors.ServerError: detail=User inactive or deleted.

CC @ntabris

**Comment by ntabris** [comment]
https://coiledcomputing.slack.com/archives/C012R2D276V/p1671628387100049

**Comment by ncclementi** [comment]
@ntabris we probably do not want to post links to slack, as this repo is public.

**Comment by dchudz** [comment]
We're not really 100% sure we're out of the woods yet, but this has been turned back on for few hours now.
