### ISSUE TITLE
Suggestion on how to deal with the CI Failed tickets

### ISSUE THREAD

**Issue by fjetter** [coiled/coiled-runtime#676]
I noticed we have many, many CI Failed tickets open. I find it very difficult to make sense of this without opening every single one of them. I would suggest a small process adjustment

- CI Failure ticket is opened. An engineer triages the issue
- Triage entails creating or linking every detected failure and/or regression to a *new* ticket with a descriptive title
- Once every failure is mapped to a ticket we close the CI Failure issue immediately.

This way we have descriptive titles and can relate duplicates more easily and the issue tracker is hopefully not flooded with false positives

cc @ncclementi @jrbourbeau

**Comment by hendrikmakait** [comment]
As discussed during yesterday's standup, we will have a dedicated "on-call" engineer responsible for triaging CI failures (following the above suggestion) and coordinating their resolution with a weekly rotation. This does _not_ include that the engineer resolves the issues by themselves, but making sure that the relevant people get notified and eventually figure out a solution.

Determining the rotation is TBD. For this week, it's me.
