### ISSUE TITLE
`coiled.errors.ClusterCreationError`, waiting for one worker

### ISSUE THREAD

**Issue by j-bennet** [coiled/coiled-runtime#743]
Failure that looks like this:

```
FAILED tests/stability/test_deadlock.py::test_repeated_merge_spill - coiled.errors.ClusterCreationError: Only 19 workers ready (was waiting for at least 20).  (cluster_id: 175720)
ERROR tests/benchmarks/test_csv.py::test_csv_basic - coiled.errors.ClusterCreationError: Only 9 workers ready (was waiting for at least 10).  (cluster_id: 175721)
```

Always seems to be waiting for just one worker.

Workflows:

* https://github.com/coiled/coiled-runtime/actions/runs/4503760077
* https://github.com/coiled/coiled-runtime/actions/runs/4506416879

**Comment by crusaderky** [comment]
CC @ntabris @shughes-uk @dchudz

**Comment by crusaderky** [comment]
Also seen in https://cloud.coiled.io/clusters/179433/details?account=dask-engineering

**Comment by ntabris** [comment]
# 175720 and 175721

Both clusters had single instance with `InternalError: Internal error on launch` error from AWS. We now try to request a replacement instance when we see this error.

# 179433 (from @crusaderky)

This cluster was starting when there were a lot of clusters (~90) also running or being started in `oss` AWS account, with lots of instances:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/46289310/228846894-56149b7a-3940-474c-9229-bbc9880f50f2.png">
