### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by mrocklin** [coiled/coiled-runtime#750]
coiled/benchmarks?

**Comment by jrbourbeau** [comment]
Renaming is something I want to do as part of https://github.com/coiled/coiled-runtime/issues/732

**Comment by mrocklin** [comment]
Anything stopping us from moving forward immediately?

**Comment by fjetter** [comment]
+1 I also think we can rename with or without the metapackage being there or not

**Comment by mrocklin** [comment]
@jrbourbeau I'm about to send this repository link to someone external and, for the purposes of that conversation I'd much rather this was called `coiled/benchmarks` rather than `coiled/coiled-runtime`.  Do you object to me changing the name?

**Comment by jrbourbeau** [comment]
Okay, that was quicker than I thought. I'be got a branch. Going to change the name and push up a PR to make sure it passes
