### ISSUE TITLE
Only 9 workers ready (was waiting for at least 10)

### ISSUE THREAD

**Issue by crusaderky** [coiled/coiled-runtime#769]
Today I got a rush of several clusters failing to start in CI with the same error:
coiled.errors.ClusterCreationError: Only 9 workers ready (was waiting for at least 10)

ERROR tests/benchmarks/test_parquet.py::test_read_spark_generated_data - coiled.errors.ClusterCreationError: Only 14 workers ready (was waiting for at least 15).  (cluster_id: 186664)
ERROR tests/benchmarks/test_custom.py::test_jobqueue - coiled.errors.ClusterCreationError: Only 9 workers ready (was waiting for at least 10).  (cluster_id: 186618)
FAILED tests/stability/test_deadlock.py::test_repeated_merge_spill - coiled.errors.ClusterCreationError: Only 19 workers ready (was waiting for at least 20).  (cluster_id: 186622)
FAILED tests/stability/test_deadlock.py::test_repeated_merge_spill - coiled.errors.ClusterCreationError: Only 19 workers ready (was waiting for at least 20).  (cluster_id: 186646)
ERROR tests/benchmarks/test_array.py::test_anom_mean[uncompressible] - coiled.errors.ClusterCreationError: Only 9 workers ready (was waiting for at least 10).  (cluster_id: 186055)

CC @ntabris @shughes-uk

**Comment by shughes-uk** [comment]
Known issue, fix coming soon https://github.com/coiled/platform/issues/1027

**Comment by shughes-uk** [comment]
should be resolved now
