### ISSUE TITLE
Environment export in CI not working

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#77]
In CI we have a step that dumps out the current environment being used right before we run tests

https://github.com/coiled/coiled-runtime/blob/0667395184944e17968a1211672de3e8b24c497a/.github/workflows/tests.yml#L60-L64

This is useful for debugging CI builds. Unfortunately, when I look at the output on CI builds it's unexpectedly empty 

```python
--
--Conda Environment (re-create this with `conda env create --name <name> -f <output_file>`)
--
name: test
channels:
  - defaults
```

EDIT: low priority, but would be good to fix at some point

**Comment by ncclementi** [comment]
Thanks for reporting this James, I can't reproduce it locally, so it must be a CI problem. 
I opened a PR to switch to conda on this line and see what happens.

**Comment by jrbourbeau** [comment]
Closed via https://github.com/coiled/coiled-runtime/pull/78
