### ISSUE TITLE
`read_parquet` + `shuffle` + `to_parquet` performance observation

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#79]
Over in https://github.com/coiled/coiled-runtime/pull/67, @sjperkins discovered that using `compute=False` + `dask.compute(...)` in the following workload:

```python
    df_shuffled = dd.read_parquet(dataset_url, storage_options=s3_storage_options)
    df_shuffled = df_shuffled.shuffle(on="x")
    result = df_shuffled.to_parquet(
        shuffled_url, compute=False, storage_options=s3_storage_options
    )
    dask.compute(result)
```

ran much faster than using the default `compute=True` in the `to_parquet` call:

```python
    df_shuffled = dd.read_parquet(dataset_url, storage_options=s3_storage_options)
    df_shuffled = df_shuffled.shuffle(on="x")
    df_shuffled.to_parquet(shuffled_url, storage_options=s3_storage_options)
```

The `compute=False` + `dask.compute(...)` snippet took ~200 seconds to run, while the `compute=True` case took ~1800 seconds to run. This was surprising as I would have expected both approaches to take roughly the same amount of time. If anything I would have expected the delayed compute to be slower due to somehow losing blockwise task fusion. 

We should investigate a bit more and open an upstream issue in `dask/dask`. Opening an issue to not lose track of this.

**Comment by sjperkins** [comment]
I suspect that memory is not released by the scheduler for some reason as there's an order of magnitude more spill when `compute=True`

**Comment by ian-r-rose** [comment]
@sjperkins do you have a sense of whether the shuffle is important to reproduce this? That is, do you see similar behavior with just a read+write?

**Comment by sjperkins** [comment]
> @sjperkins do you have a sense of whether the shuffle is important to reproduce this? That is, do you see similar behavior with just a read+write?

I don't have a sense if it's important. I never tried without the shuffle because it was central to the stability test.

**Comment by jrbourbeau** [comment]
> do you have a sense of whether the shuffle is important to reproduce this? That is, do you see similar behavior with just a read+write?

Testing out in https://github.com/coiled/coiled-runtime/pull/85

**Comment by jcrist** [comment]
There's no reason to have a different code path in `to_parquet` for this, I've removed the branch in https://github.com/dask/dask/pull/8982 so they're effectively the same.

**Comment by jrbourbeau** [comment]
Closing as the upstream fix from @jcrist fixed this performance issue (xref https://github.com/coiled/coiled-runtime/pull/93#issuecomment-1110448275)

**Comment by ian-r-rose** [comment]
I'd like to look into this a bit more to understand why this happened (and if other invocations of `compute_as_if_collection` have the same defect)

**Comment by jrbourbeau** [comment]
Agreed that'd be good to understand (https://github.com/dask/dask/pull/8982#issuecomment-1111508716). Mind opening a new issue in `dask/dask` so we don't loose track of it?

**Comment by ian-r-rose** [comment]
Sure

**Comment by ian-r-rose** [comment]
https://github.com/dask/dask/issues/8991
