### ISSUE TITLE
[h2o benchmark] Align with evangelism on benchmark infrastructure

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#8]
Collaborate with the Coiled evangelism team to ensure the benchmarking infrastructure we produce are in alignment with their needs

**Comment by shughes-uk** [comment]
Happy to help with any questions on getting the infrastructure you need. The #engineering-clusters channel would also be a good place to ask.

**Comment by MrPowers** [comment]
Cool, joined #engineering-clusters, thanks @shughes-uk!!

**Comment by ncclementi** [comment]
Closing this as obsolete. We have a separate tracking ticket for a blogpost on h2o benchmarks as well as we are about to invest work to improve the performance of the queries. 

Closing in favor of https://github.com/orgs/coiled/projects/12/views/3
