### ISSUE TITLE
Pre-release versions of coiled-runtime

### ISSUE THREAD

**Issue by shughes-uk** [coiled/coiled-runtime#86]
It would be very helpful for us to have pre-releases of coiled-runtime available, either cut directly from dask `main` or a hand selected more recent version.

We could use this internally at coiled on our staging deployment as well to test things before promoting it to a full release

**Comment by dchudz** [comment]
n.b.: We'd probably want to having staging.coiledhq.com use the pre-release in its default software environment, which will probably require changes to https://github.com/coiled/software-environments/.

**Comment by jrbourbeau** [comment]
Thanks for the additional info @dchudz

I'll suggest we add a new GHA workflow which runs on a cron and publishes a nightly version of `coiled-runtime` that uses the nightly of `dask` and `distributed` conda packages that are published on the `dask` conda channel https://anaconda.org/dask. I suspect we can also reuse some of the logic around how those [`dask` and `distributed` nightlies are generated](https://github.com/dask/distributed/tree/main/continuous_integration/recipes) here for publishing a nightly `coiled-runtime`.

**Comment by dchudz** [comment]
Sounds great, I think. After that someone could shift our GHA's in https://github.com/coiled/software-environments/ to use the nightly for staging.

In the meantime I think @shughes-uk is going to hack the default environment on staging to use latest.

**Comment by jrbourbeau** [comment]
> In the meantime I think @shughes-uk is going to hack the default environment on staging to use latest.

Just checking in -- was a temporary hack possible? I'm thinking about prioritization and wanted to get a sense for how critical getting a pre-release process out is

**Comment by shughes-uk** [comment]
@jrbourbeau yes I hacked it in. My highest priority ask now is just getting a new version of dask/distributed out and into coiled runtime, the stability difference is huge with the very minor plugin tweak!
