### ISSUE TITLE
Add usage instructions

### ISSUE THREAD

**Issue by MrPowers** [coiled/coiled-runtime#87]
Here's my understanding of the current usage instructions.  Should we add these to the README?

Create a software environment with the coiled-runtime.

```python
coiled.create_software_environment(
    name = "my_env",
    conda = {"channels": ["conda-forge", "coiled"],
             "dependencies": ["coiled-runtime", "Python=3.9.12"]
            },
)
```

Add the `conda-forge` and `coiled` channels if you haven't done so already:

```
conda config --add channels conda-forge
conda config --add channels coiled
```

Create a local environment:

```
conda create -n crt -y python=3.9.12 coiled-runtime
```

Spin up Coiled clusters like this:

```python
cluster = coiled.Cluster(
    name="github-json",
    software="matthew-powers/my_env", 
    n_workers=10,
)
```

This will ensure that the local software versions and cluster software versions are the same.

**Comment by ncclementi** [comment]
@MrPowers, Sarah has been working on updating this on the Coiled documentation see https://gitlab.com/coiled/cloud/-/merge_requests/4449#note_923189595

I think since this repo would go beyond Coiled usage, I'd be skeptical to add specific coiled docs here.

**Comment by jrbourbeau** [comment]
Yeah, I agree with @ncclementi. This type of documentation seems useful, but better suited for the Coiled docs
