### ISSUE TITLE
Initial conda-forge release

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#9]
@hayesgb, @ncclementi mentioned it was decided that we should do a public release on conda-forge of the Coiled Runtime. There was a discussion on Slack around how to go about this technically, which I'll summarize below:

- You cannot upload a package to conda-forge that isn't built by the conda-forge bots (i.e. going through the normal `staged-recipes` -> `package-feedstock` route)
- The only additional content in the `coiled-runtime` repository is the test suite we run against the pinned package versions in the runtime. These are run today in this repository with GitHub actions, but we could package the tests up and _also_ run them during the conda-forge build process. I see this providing value in the future, but not as a requirement for an initial release (feedback on this from others is welcome)
- Next steps would be to issue a release (on GitHub) of the Coiled Runtime (at a minimum we need a license file included in the release) and then go through the normal `staged-recipes` -> `coiled-runtime-feedstock` process to get the runtime onto conda-forge. 

## Questions

- Are the existing version pins what we want to include in the initial public release? 

https://github.com/coiled/coiled-runtime/blob/96b876dbd1e950a42e50d6890ad72986d05e8611/continuous_integration/recipe/meta.yaml#L13-L44

My guess is we want to ping to an earlier release on `dask` + `distributed` from January since there have been deadlocks reported with more recent versions. 

- Packages on conda-forge need a license. What license should we use for the Coiled Runtime? Dask itself uses BSD-3 -- is that appropriate here too? 
- ...

**Comment by hayesgb** [comment]
Thanks @jrbourbeau.  

I updated the package versions and added a license.  I also opened a PR with conda-forge.  I'll ping you tomorrow to touch base.

**Comment by ncclementi** [comment]
I'm adding here the coiled-runtime staged recipe PR link here so it's easier to track. We are still waiting for a review. 
https://github.com/conda-forge/staged-recipes/pull/18611

**Comment by jrbourbeau** [comment]
`coiled-runtime` is on conda-forge now https://github.com/conda-forge/staged-recipes/pull/18611 🎉
