### ISSUE TITLE
Stop testing windows and mac?

### ISSUE THREAD

**Issue by mrocklin** [coiled/coiled-runtime#96]
Since most of this code just calls Coiled and asks it to do things it's not clear to me that there is much value to cross-platform testing here.  Really we're just mostly testing that the client APIs work, and this seems more relevant for the tests in each project.  

I propose dropping windows/osx testing because it probably doesn't bring in much additional signal (Coiled is running Linux regardless).  Thoughts?

**Comment by ntabris** [comment]
I mostly don't know what I'm talking about but do we test that Win/Mac solves will work and not get major version mismatch with Linux solve running in the cloud? (I've had experiences with packages updating for some but not all OS's in the past, not sure if that's likely given the set of packages we're putting in runtime or if we already have some mechanism for ensuring that we don't pin Linux-only update version in the runtime.)

**Comment by mrocklin** [comment]
Yeah, and if we were testing software environments a lot here I agree that it might make sense to test.  However, we're mostly testing that Dask works at scale here.  I don't think that adding the other platforms on the client side add a ton of value.  At least, I don't think that they add enough value to triple the testing infrastructure cost.

**Comment by jrbourbeau** [comment]
Thank @mrocklin. I agree our current build matrix is probably overkill at the moment. I see a couple of reasons for keeping some Windows/macOS builds:

- Make sure the current set of runtime package pinnings are able to solve on all platforms
- Provide some coverage against problems like "package X is broken on Windows", which occasionally happens

I'd propose we keep Windows/macOS builds, but only for a single Python version. Thoughts?
