### ISSUE TITLE
Stability Testing Report

### ISSUE THREAD

**Issue by sjperkins** [coiled/coiled-runtime#98]
The `distributed` team wishes to create a Stability Test for tracking how changes to the distributed server affect stability. The following ideas might be useful in scoping:

- The relevant CI (Github Actions) could produce stability report artefacts
- Code from here could be leveraged to generate the report: https://github.com/dask/distributed/blob/main/continuous_integration/scripts/test_report.py
- Should we break the above into it's own repo to avoid cut-n-paste?
- The stability report could be published here https://dask.org/distributed/stability_report.html
- Relevant people could be alerted, for example by email or on slack
- It could include the report cost of run (related to coiled account we choose to use for this)

**Comment by ncclementi** [comment]
@ian-r-rose should we close this one in favor of https://github.com/coiled/coiled-runtime/issues/138

**Comment by ncclementi** [comment]
Closing in favor of https://github.com/coiled/coiled-runtime/issues/138
